/**
 * S1 – API & SOURCE MAP (Google Studio / Grounding Edition)
 * =========================================================
 * Comprehensive mapping of authoritative REST APIs and Google Search Grounding
 * source domains across the 10 critical S1 asset & fund categories.
 */

export interface S1SourceItem {
  id: string;
  nameFa: string;
  nameEn: string;
  categoryFa: string;
  categoryEn: string;
  apiEndpoint: string;
  groundingSourceUrl: string;
  groundingDomain: string;
  requiresIranProxy: boolean;
  notesFa?: string;
}

export interface S1CategoryGroup {
  number: number;
  titleFa: string;
  titleEn: string;
  descriptionFa: string;
  items: S1SourceItem[];
}

export const S1_FULL_SOURCE_MAP: S1CategoryGroup[] = [
  {
    number: 1,
    titleFa: '۱) اقتصاد کلان ایران (ارز، طلا و سکه)',
    titleEn: 'Iran Macro Economy (FX, Gold & Coins)',
    descriptionFa: 'شامل دلار آزاد، تتر، طلای ۱۸ عیار، سکه امامی و حباب سکه',
    items: [
      {
        id: 'usd_free',
        nameFa: 'دلار آزاد تهران',
        nameEn: 'Free Market USD / Toman',
        categoryFa: 'اقتصاد کلان ایران',
        categoryEn: 'Iran Macro',
        apiEndpoint: 'https://api.masadir.io/fx/usd',
        groundingSourceUrl: 'https://www.xe.com/currencyconverter/',
        groundingDomain: 'xe.com',
        requiresIranProxy: false,
        notesFa: 'همچنین اتصال به شبکه Bonbast و TGJU جهت تطبیق نهایی',
      },
      {
        id: 'usdt_tether',
        nameFa: 'تتر (USDT)',
        nameEn: 'Tether USDT / IRT',
        categoryFa: 'اقتصاد کلان ایران',
        categoryEn: 'Iran Macro',
        apiEndpoint: 'https://api.masadir.io/fx/usdt',
        groundingSourceUrl: 'https://www.coingecko.com/en/coins/tether',
        groundingDomain: 'coingecko.com',
        requiresIranProxy: false,
        notesFa: 'اتصال مستقیم به اردر‌بوک بدون تحریم نوبیتکس (api.nobitex.ir)',
      },
      {
        id: 'gold_18k',
        nameFa: 'طلای ۱۸ عیار (گرم)',
        nameEn: '18 Karat Gold (Per Gram)',
        categoryFa: 'اقتصاد کلان ایران',
        categoryEn: 'Iran Macro',
        apiEndpoint: 'https://api.valleyapi.io/gold/iran/18k',
        groundingSourceUrl: 'https://www.goldprice.org/',
        groundingDomain: 'goldprice.org',
        requiresIranProxy: false,
        notesFa: 'محاسبه همزمان با فرمول ریاضی S1 (اونس × دلار × ۰.۷۵۰ / ۳۱.۱۰۳۵)',
      },
      {
        id: 'seke_emami',
        nameFa: 'سکه تمام طرح جدید (امامی)',
        nameEn: 'Emami Gold Coin',
        categoryFa: 'اقتصاد کلان ایران',
        categoryEn: 'Iran Macro',
        apiEndpoint: 'https://api.valleyapi.io/gold/coin/emami',
        groundingSourceUrl: 'https://www.tgju.org/coin-emami',
        groundingDomain: 'tgju.org',
        requiresIranProxy: false,
        notesFa: 'وزن ۸.۱۳۳ گرم طلای ۲۲ عیار (عیار ۹۰۰)',
      },
      {
        id: 'coin_bubble',
        nameFa: 'حباب سکه امامی',
        nameEn: 'Gold Coin Premium / Bubble',
        categoryFa: 'اقتصاد کلان ایران',
        categoryEn: 'Iran Macro',
        apiEndpoint: 'https://api.valleyapi.io/gold/coin/premium',
        groundingSourceUrl: 'https://www.tgju.org/',
        groundingDomain: 'tgju.org',
        requiresIranProxy: false,
        notesFa: 'محاسبه تفاوت درصد قیمت بازاری با ارزش ذاتی طلا',
      },
    ],
  },
  {
    number: 2,
    titleFa: '۲) بازارهای جهانی و کامودیتی‌ها',
    titleEn: 'Global Markets & Commodities',
    descriptionFa: 'اونس طلا، شاخص دلار، نفت برنت، شاخص نوسان و شاخص ترس و طمع جهانی',
    items: [
      {
        id: 'gold_ounce',
        nameFa: 'اونس جهانی طلا (XAU/USD)',
        nameEn: 'Spot Gold Ounce (XAUUSD)',
        categoryFa: 'بازارهای جهانی',
        categoryEn: 'Global Markets',
        apiEndpoint: 'https://api.alltick.co/commodities/xauusd',
        groundingSourceUrl: 'https://www.tradingview.com/symbols/XAUUSD/',
        groundingDomain: 'tradingview.com',
        requiresIranProxy: false,
        notesFa: 'اتصال رزرو به Yahoo Finance Chart API (GC=F)',
      },
      {
        id: 'dxy_index',
        nameFa: 'شاخص دلار آمریکا (DXY)',
        nameEn: 'US Dollar Index (DXY)',
        categoryFa: 'بازارهای جهانی',
        categoryEn: 'Global Markets',
        apiEndpoint: 'https://api.alltick.co/indices/dxy',
        groundingSourceUrl: 'https://www.tradingview.com/symbols/DXY/',
        groundingDomain: 'tradingview.com',
        requiresIranProxy: false,
        notesFa: 'اتصال رزرو به Yahoo Finance (DX-Y.NYB)',
      },
      {
        id: 'brent_oil',
        nameFa: 'نفت خام برنت (Brent)',
        nameEn: 'Brent Crude Oil',
        categoryFa: 'بازارهای جهانی',
        categoryEn: 'Global Markets',
        apiEndpoint: 'https://api.masadir.io/energy/brent',
        groundingSourceUrl: 'https://www.investing.com/commodities/brent-oil',
        groundingDomain: 'investing.com',
        requiresIranProxy: false,
        notesFa: 'اتصال رزرو به Yahoo Finance (BZ=F)',
      },
      {
        id: 'vix_index',
        nameFa: 'شاخص نوسان CBOE (VIX)',
        nameEn: 'CBOE Volatility Index (VIX)',
        categoryFa: 'بازارهای جهانی',
        categoryEn: 'Global Markets',
        apiEndpoint: 'https://api.alltick.co/indices/vix',
        groundingSourceUrl: 'https://www.cboe.com/tradable_products/vix/',
        groundingDomain: 'cboe.com',
        requiresIranProxy: false,
        notesFa: 'سنجه ریسک‌گریزی و تلاطم بازارهای سهام بین‌الملل',
      },
      {
        id: 'global_fear_greed',
        nameFa: 'شاخص ترس و طمع جهانی CNN',
        nameEn: 'CNN Fear & Greed Index',
        categoryFa: 'بازارهای جهانی',
        categoryEn: 'Global Markets',
        apiEndpoint: 'https://fear-and-greed-index.p.rapidapi.com/',
        groundingSourceUrl: 'https://money.cnn.com/data/fear-and-greed/',
        groundingDomain: 'money.cnn.com',
        requiresIranProxy: false,
        notesFa: 'پایش احساسات و سنتیمنت کلی وال‌استریت',
      },
    ],
  },
  {
    number: 3,
    titleFa: '۳) بیت‌کوین و بازار کریپتو',
    titleEn: 'Bitcoin & Crypto Market',
    descriptionFa: 'قیمت بیت‌کوین، اتریوم، دامیننس، ارزش کل بازار، ورود ETF، فاندینگ ریت و احساسات',
    items: [
      {
        id: 'btc_price',
        nameFa: 'قیمت بیت‌کوین (BTC/USD)',
        nameEn: 'Bitcoin Spot Price',
        categoryFa: 'بیت‌کوین و کریپتو',
        categoryEn: 'Crypto',
        apiEndpoint: 'https://api.alltick.co/crypto/btcusd',
        groundingSourceUrl: 'https://coinmarketcap.com/currencies/bitcoin/',
        groundingDomain: 'coinmarketcap.com',
        requiresIranProxy: false,
        notesFa: 'اتصال مستقیم به بایننس و کوین‌گکو',
      },
      {
        id: 'eth_price',
        nameFa: 'قیمت اتریوم (ETH/USD)',
        nameEn: 'Ethereum Spot Price',
        categoryFa: 'بیت‌کوین و کریپتو',
        categoryEn: 'Crypto',
        apiEndpoint: 'https://api.coingecko.com/api/v3/coins/ethereum',
        groundingSourceUrl: 'https://www.coingecko.com/en/coins/ethereum',
        groundingDomain: 'coingecko.com',
        requiresIranProxy: false,
      },
      {
        id: 'btc_dominance',
        nameFa: 'دامیننس بیت‌کوین (BTC.D)',
        nameEn: 'Bitcoin Market Dominance',
        categoryFa: 'بیت‌کوین و کریپتو',
        categoryEn: 'Crypto',
        apiEndpoint: 'https://api.alltick.co/crypto/btc.dominance',
        groundingSourceUrl: 'https://www.tradingview.com/symbols/BTC.D/',
        groundingDomain: 'tradingview.com',
        requiresIranProxy: false,
      },
      {
        id: 'crypto_market_cap',
        nameFa: 'ارزش کل بازار کریپتو (Total Market Cap)',
        nameEn: 'Total Crypto Market Cap',
        categoryFa: 'بیت‌کوین و کریپتو',
        categoryEn: 'Crypto',
        apiEndpoint: 'https://api.coinmarketcap.com/data-api/v3/global-metrics/quotes/latest',
        groundingSourceUrl: 'https://coinmarketcap.com/charts/',
        groundingDomain: 'coinmarketcap.com',
        requiresIranProxy: false,
      },
      {
        id: 'btc_etf_netflow',
        nameFa: 'خالص ورود/خروج ETF بیت‌کوین',
        nameEn: 'Bitcoin ETF Net Inflow/Outflow',
        categoryFa: 'بیت‌کوین و کریپتو',
        categoryEn: 'Crypto',
        apiEndpoint: 'https://api.coinglass.com/api/etf/netflow',
        groundingSourceUrl: 'https://www.coinglass.com/etf',
        groundingDomain: 'coinglass.com',
        requiresIranProxy: false,
      },
      {
        id: 'crypto_funding_rate',
        nameFa: 'نرخ تامین مالی فیوچرز (Funding Rate)',
        nameEn: 'Crypto Futures Funding Rate',
        categoryFa: 'بیت‌کوین و کریپتو',
        categoryEn: 'Crypto',
        apiEndpoint: 'https://api.coinglass.com/api/futures/funding',
        groundingSourceUrl: 'https://www.coinglass.com/funding',
        groundingDomain: 'coinglass.com',
        requiresIranProxy: false,
      },
      {
        id: 'crypto_open_interest',
        nameFa: 'موقعیت‌های باز تعهدی (Open Interest)',
        nameEn: 'Crypto Futures Open Interest',
        categoryFa: 'بیت‌کوین و کریپتو',
        categoryEn: 'Crypto',
        apiEndpoint: 'https://api.coinglass.com/api/futures/openInterest',
        groundingSourceUrl: 'https://www.coinglass.com/oi',
        groundingDomain: 'coinglass.com',
        requiresIranProxy: false,
      },
      {
        id: 'crypto_fear_greed',
        nameFa: 'شاخص ترس و طمع کریپتو',
        nameEn: 'Crypto Fear & Greed Index',
        categoryFa: 'بیت‌کوین و کریپتو',
        categoryEn: 'Crypto',
        apiEndpoint: 'https://api.alternative.me/fng/',
        groundingSourceUrl: 'https://alternative.me/crypto/fear-and-greed-index/',
        groundingDomain: 'alternative.me',
        requiresIranProxy: false,
      },
    ],
  },
  {
    number: 4,
    titleFa: '۴) بورس اوراق بهادار تهران',
    titleEn: 'Tehran Stock Exchange (TSE)',
    descriptionFa: 'شاخص کل، شاخص هم‌وزن، ارزش معاملات خرد و خالص ورود پول حقیقی (با Scraping + پروکسی ایران)',
    items: [
      {
        id: 'tse_index',
        nameFa: 'شاخص کل بورس تهران',
        nameEn: 'TSE Overall Index',
        categoryFa: 'بورس تهران',
        categoryEn: 'TSE',
        apiEndpoint: 'https://tsetmc.com/instinfo/INDEX',
        groundingSourceUrl: 'https://tsetmc.com/Index',
        groundingDomain: 'tsetmc.com',
        requiresIranProxy: true,
        notesFa: 'دسترسی مستقیم از IPهای خارجی مسدود است؛ استخراج از طریق Grounding و Proxy ایران',
      },
      {
        id: 'tse_equal_weight',
        nameFa: 'شاخص کل هم‌وزن',
        nameEn: 'TSE Equal-Weight Index',
        categoryFa: 'بورس تهران',
        categoryEn: 'TSE',
        apiEndpoint: 'https://tsetmc.com/instinfo/INDEXH',
        groundingSourceUrl: 'https://tsetmc.com/Index',
        groundingDomain: 'tsetmc.com',
        requiresIranProxy: true,
      },
      {
        id: 'tse_retail_volume',
        nameFa: 'ارزش معاملات خرد (سهام و حق تقدم)',
        nameEn: 'TSE Retail Trade Volume',
        categoryFa: 'بورس تهران',
        categoryEn: 'TSE',
        apiEndpoint: 'https://databourse.ir/api/retail',
        groundingSourceUrl: 'https://databourse.ir/retail',
        groundingDomain: 'databourse.ir',
        requiresIranProxy: true,
      },
      {
        id: 'tse_real_money_flow',
        nameFa: 'ورود/خروج پول حقیقی (میلیارد تومان)',
        nameEn: 'Individual Money Net Inflow',
        categoryFa: 'بورس تهران',
        categoryEn: 'TSE',
        apiEndpoint: 'https://bourseview.ir/api/realmoney',
        groundingSourceUrl: 'https://bourseview.ir/real-money',
        groundingDomain: 'bourseview.ir',
        requiresIranProxy: true,
      },
    ],
  },
  {
    number: 5,
    titleFa: '۵) صندوق درآمد ثابت افران (AFRAN)',
    titleEn: 'Fixed Income ETF (AFRAN)',
    descriptionFa: 'پایش قیمت پایانی، NAV ابطال و حجم معاملات صندوق درآمد ثابت با درآمد باثبات',
    items: [
      {
        id: 'afran_close',
        nameFa: 'قیمت پایانی و آخرین معامله افران',
        nameEn: 'AFRAN Closing & Last Price',
        categoryFa: 'صندوق درآمد ثابت',
        categoryEn: 'Fixed Income Fund',
        apiEndpoint: 'https://databourse.ir/symbol/%D8%A7%D9%81%D8%B1%D8%A7%D9%86',
        groundingSourceUrl: 'https://rahavard365.com/asset/7799/%D8%A7%D9%81%D8%B1%D8%A7%D9%86',
        groundingDomain: 'rahavard365.com',
        requiresIranProxy: false,
        notesFa: 'منبع باز و بدون لاگین ره‌آورد ۳۶۵ و دیتابورس (تایید شده توسط کاربر)',
      },
      {
        id: 'afran_nav',
        nameFa: 'NAV ابطال و نسبت P/NAV افران',
        nameEn: 'AFRAN Redemption NAV & P/NAV',
        categoryFa: 'صندوق درآمد ثابت',
        categoryEn: 'Fixed Income Fund',
        apiEndpoint: 'https://api.fipiran.ir/nav/AFRAN',
        groundingSourceUrl: 'https://databourse.ir/symbol/%D8%A7%D9%81%D8%B1%D8%A7%D9%86',
        groundingDomain: 'databourse.ir',
        requiresIranProxy: false,
        notesFa: 'استخراج ارزش خالص دارایی‌ها و اختلاف درصد NAV بدون تحریم IP',
      },
      {
        id: 'afran_volume',
        nameFa: 'حجم، ارزش معاملات و سرانه خرید/فروش افران',
        nameEn: 'AFRAN Trade Volume, Value & Real Per-Capita',
        categoryFa: 'صندوق درآمد ثابت',
        categoryEn: 'Fixed Income Fund',
        apiEndpoint: 'https://databourse.ir/symbol/%D8%A7%D9%81%D8%B1%D8%A7%D9%86',
        groundingSourceUrl: 'https://rahavard365.com/asset/7799/%D8%A7%D9%81%D8%B1%D8%A7%D9%86',
        groundingDomain: 'rahavard365.com',
        requiresIranProxy: false,
        notesFa: 'بررسی قدرت خریدار حقیقی و خالص ورود/خروج نقدینگی',
      },
    ],
  },
  {
    number: 6,
    titleFa: '۶) صندوق طلای عیار (AIAR)',
    titleEn: 'Gold ETF (AIAR)',
    descriptionFa: 'پایش نماد صندوق سرمایه‌گذاری پشتوانه طلای لوتوس / عیار مفید',
    items: [
      {
        id: 'aiar_close',
        nameFa: 'قیمت پایانی عیار',
        nameEn: 'AIAR Closing Price',
        categoryFa: 'صندوق طلا',
        categoryEn: 'Gold ETF',
        apiEndpoint: 'https://tsetmc.com/api/closing/AIAR',
        groundingSourceUrl: 'https://tsetmc.com/instinfo/AIAR',
        groundingDomain: 'tsetmc.com',
        requiresIranProxy: true,
      },
      {
        id: 'aiar_nav',
        nameFa: 'NAV ابطال عیار',
        nameEn: 'AIAR Redemption NAV',
        categoryFa: 'صندوق طلا',
        categoryEn: 'Gold ETF',
        apiEndpoint: 'https://api.fipiran.ir/nav/AIAR',
        groundingSourceUrl: 'https://fipiran.com/funds/AIAR',
        groundingDomain: 'fipiran.com',
        requiresIranProxy: false,
      },
    ],
  },
  {
    number: 7,
    titleFa: '۷) صندوق سهامی خبرگان (KHABR)',
    titleEn: 'Equity ETF (KHABR)',
    descriptionFa: 'پایش قیمت پایانی و NAV ابطال صندوق سهامی مشترک خبرگان',
    items: [
      {
        id: 'khabr_close',
        nameFa: 'قیمت پایانی خبرگان',
        nameEn: 'KHABR Closing Price',
        categoryFa: 'صندوق سهامی',
        categoryEn: 'Equity Fund',
        apiEndpoint: 'https://tsetmc.com/api/closing/KHABR',
        groundingSourceUrl: 'https://tsetmc.com/instinfo/KHABR',
        groundingDomain: 'tsetmc.com',
        requiresIranProxy: true,
      },
      {
        id: 'khabr_nav',
        nameFa: 'NAV ابطال خبرگان',
        nameEn: 'KHABR Redemption NAV',
        categoryFa: 'صندوق سهامی',
        categoryEn: 'Equity Fund',
        apiEndpoint: 'https://api.fipiran.ir/nav/KHABR',
        groundingSourceUrl: 'https://fipiran.com/funds/KHABR',
        groundingDomain: 'fipiran.com',
        requiresIranProxy: false,
      },
    ],
  },
  {
    number: 8,
    titleFa: '۸) صندوق اهرمی توان (TAVAN)',
    titleEn: 'Leveraged ETF (TAVAN)',
    descriptionFa: 'پایش قیمت پایانی و NAV ابطال صندوق سرمایه‌گذاری اهرمی توان مفید',
    items: [
      {
        id: 'tavan_close',
        nameFa: 'قیمت پایانی توان اهرمی',
        nameEn: 'TAVAN Closing Price',
        categoryFa: 'صندوق اهرمی',
        categoryEn: 'Leveraged Fund',
        apiEndpoint: 'https://tsetmc.com/api/closing/TAVAN',
        groundingSourceUrl: 'https://tsetmc.com/instinfo/TAVAN',
        groundingDomain: 'tsetmc.com',
        requiresIranProxy: true,
      },
      {
        id: 'tavan_nav',
        nameFa: 'NAV ابطال توان',
        nameEn: 'TAVAN Redemption NAV',
        categoryFa: 'صندوق اهرمی',
        categoryEn: 'Leveraged Fund',
        apiEndpoint: 'https://api.fipiran.ir/nav/TAVAN',
        groundingSourceUrl: 'https://fipiran.com/funds/TAVAN',
        groundingDomain: 'fipiran.com',
        requiresIranProxy: false,
      },
    ],
  },
  {
    number: 9,
    titleFa: '۹) سایر صندوق‌های طلا (زر، کهربا، گوهر، نفیس، مثقال)',
    titleEn: 'Other Gold ETFs (ZAR, KAHROBA, GOHAR, NAFIS, MESGHAL)',
    descriptionFa: 'پایش تجمیعی قیمت‌ها و NAV صندوق‌های طلای بورس کالا',
    items: [
      {
        id: 'zar_gold',
        nameFa: 'صندوق طلای زرین (زر)',
        nameEn: 'ZAR Gold ETF',
        categoryFa: 'صندوق‌های طلا',
        categoryEn: 'Gold ETFs',
        apiEndpoint: 'https://tsetmc.com/api/inst/ZAR',
        groundingSourceUrl: 'https://tsetmc.com/instinfo/ZAR',
        groundingDomain: 'tsetmc.com',
        requiresIranProxy: true,
      },
      {
        id: 'kahroba_gold',
        nameFa: 'صندوق طلای کهربا',
        nameEn: 'KAHROBA Gold ETF',
        categoryFa: 'صندوق‌های طلا',
        categoryEn: 'Gold ETFs',
        apiEndpoint: 'https://tsetmc.com/api/inst/KAHROBA',
        groundingSourceUrl: 'https://tsetmc.com/instinfo/KAHROBA',
        groundingDomain: 'tsetmc.com',
        requiresIranProxy: true,
      },
      {
        id: 'gohar_gold',
        nameFa: 'صندوق طلای گوهر',
        nameEn: 'GOHAR Gold ETF',
        categoryFa: 'صندوق‌های طلا',
        categoryEn: 'Gold ETFs',
        apiEndpoint: 'https://tsetmc.com/api/inst/GOHAR',
        groundingSourceUrl: 'https://tsetmc.com/instinfo/GOHAR',
        groundingDomain: 'tsetmc.com',
        requiresIranProxy: true,
      },
      {
        id: 'nafis_gold',
        nameFa: 'صندوق طلای نفیس',
        nameEn: 'NAFIS Gold ETF',
        categoryFa: 'صندوق‌های طلا',
        categoryEn: 'Gold ETFs',
        apiEndpoint: 'https://tsetmc.com/api/inst/NAFIS',
        groundingSourceUrl: 'https://tsetmc.com/instinfo/NAFIS',
        groundingDomain: 'tsetmc.com',
        requiresIranProxy: true,
      },
      {
        id: 'mesghal_gold',
        nameFa: 'صندوق طلای مثقال',
        nameEn: 'MESGHAL Gold ETF',
        categoryFa: 'صندوق‌های طلا',
        categoryEn: 'Gold ETFs',
        apiEndpoint: 'https://tsetmc.com/api/inst/MESGHAL',
        groundingSourceUrl: 'https://tsetmc.com/instinfo/MESGHAL',
        groundingDomain: 'tsetmc.com',
        requiresIranProxy: true,
      },
    ],
  },
  {
    number: 10,
    titleFa: '۱۰) صندوق‌های نقره (سیلور، نقرین، نقرابی)',
    titleEn: 'Silver ETFs (SILVER, NOGHRIN, NOGHRABI)',
    descriptionFa: 'پایش قیمت‌های معاملاتی و NAV صندوق‌های نقره بورس کالا',
    items: [
      {
        id: 'silver_fund',
        nameFa: 'صندوق نقره سیلور (SILVER)',
        nameEn: 'Silver ETF (SILVER)',
        categoryFa: 'صندوق‌های نقره',
        categoryEn: 'Silver ETFs',
        apiEndpoint: 'https://tsetmc.com/api/inst/SILVER',
        groundingSourceUrl: 'https://tsetmc.com/instinfo/SILVER',
        groundingDomain: 'tsetmc.com',
        requiresIranProxy: true,
      },
      {
        id: 'noghrin_fund',
        nameFa: 'صندوق نقره نقرین (NOGHRIN)',
        nameEn: 'Silver ETF (NOGHRIN)',
        categoryFa: 'صندوق‌های نقره',
        categoryEn: 'Silver ETFs',
        apiEndpoint: 'https://tsetmc.com/api/inst/NOGHRIN',
        groundingSourceUrl: 'https://tsetmc.com/instinfo/NOGHRIN',
        groundingDomain: 'tsetmc.com',
        requiresIranProxy: true,
      },
      {
        id: 'noghrabi_fund',
        nameFa: 'صندوق نقره نقرابی (NOGHRABI)',
        nameEn: 'Silver ETF (NOGHRABI)',
        categoryFa: 'صندوق‌های نقره',
        categoryEn: 'Silver ETFs',
        apiEndpoint: 'https://tsetmc.com/api/inst/NOGHRABI',
        groundingSourceUrl: 'https://tsetmc.com/instinfo/NOGHRABI',
        groundingDomain: 'tsetmc.com',
        requiresIranProxy: true,
      },
    ],
  },
];

/**
 * Builds an official Google Search Grounding prompt incorporating the authoritative domains
 */
export function buildS1GroundingSearchPrompt(jalaliDateVerbose: string, miladiDate: string): string {
  return `شما تحلیل‌گر ارشد مالی سیستم S1 هستید.
تاریخ پایش: ${jalaliDateVerbose} مصادف با ${miladiDate}.

لطفاً بر اساس نگاشت منابع معتبر S1 (API & Source Map) و با استفاده از موتور Google Search Grounding، مقادیر زنده را از دامنه‌های زیر جستجو و استخراج فرمایید:

۱. اقتصاد کلان ایران (xe.com, coingecko.com, goldprice.org, tgju.org):
   - نرخ دلار آزاد تهران و نرخ تتر
   - قیمت هر گرم طلای ۱۸ عیار، سکه تمام امامی و درصد حباب سکه

۲. بازارهای جهانی (tradingview.com, investing.com, cboe.com, money.cnn.com):
   - اونس جهانی طلا (XAUUSD)
   - شاخص دلار (DXY)، نفت برنت (Brent)، شاخص VIX و Fear & Greed جهانی

۳. بیت‌کوین و کریپتو (coinmarketcap.com, coingecko.com, coinglass.com, alternative.me):
   - قیمت بیت‌کوین و اتریوم، دامیننس BTC، خالص ورود ETF، فاندینگ ریت و شاخص F&G کریپتو

۴. بورس ایران و صندوق‌ها (tsetmc.com, databourse.ir, bourseview.ir, fipiran.com):
   - شاخص کل و هم‌وزن، ارزش معاملات خرد و ورود/خروج پول حقیقی
   - قیمت پایانی و NAV ابطال صندوق‌های کلیدی (افران AFRAN، عیار AIAR، خبرگان KHABR، توان TAVAN، زر، کهربا، سیلور و نقرین)`;
}
