import {
  MarketScoreItem,
  InputMetric,
  FundItem,
  SystemS1Signal,
  TelegramConfig,
  SystemHistoryLog,
  PortfolioSummary,
  PortfolioAssetItem,
  PortfolioHistoryPoint,
  PortfolioTradeItem,
  PortfolioPendingOrder,
  NewsItem,
  SystemicRiskItem,
  AiDailySummary,
  SRIModel,
  DailyChecklistItem,
  S1V13RulebookSection,
} from './types';
import {
  getLiveJalaliDateString,
  getLiveJalaliVerboseDate,
  getTehranTimeString,
  getLiveDateTimeString,
} from './utils/dateHelper';

export const initialMarketScores: MarketScoreItem[] = [
  {
    id: 'bourse',
    name: 'بورس ایران',
    nameEn: 'Iran Stock Exchange (TSETMC)',
    symbol: 'TSE',
    icon: 'show_chart',
    score: 88,
    sentiment: 'Strong Bull',
    trafficLight: 'green',
    trafficLightLabel: '🟢 چراغ سبز (۸۸/۱۰۰) - بسیار قوی؛ جهش تاریخی شاخص کل به ۶,۳۸۶,۵۷۶ واحد و ورود پرحجم نقدینگی',
    primaryColor: '#10b981',
    metrics: [
      { label: 'ورود پول حقیقی:', value: '+۱,۴۸۰ میلیارد ت', status: 'positive' },
      { label: 'ارزش معاملات خرد:', value: '۵۴,۲۰۰ میلیارد ت', status: 'positive' },
      { label: 'شاخص کل:', value: '۶,۳۸۶,۵۷۶ (+۲.۶۱٪)', status: 'positive' },
      { label: 'قدرت خریدار:', value: '۱.۸۲ (سرانه بسیار قوی)', status: 'positive' },
    ],
    description: 'طبق فرمول ۱۰۰ امتیازی S1، ورود پرقدرت ۱,۴۸۰ میلیارد تومانی پول حقیقی و ارزش معاملات ۵۴ همتی، تایید کامل چراغ سبز را محقق کرده است.',
    threeConfirmations: {
      confirmationTitle: 'قانون تایید سه‌گانه بورس ایران (S1 Triple Confirmation)',
      ruleSummary: 'الزام رول‌بوک S1 برای خرید سهام/صندوق اهرمی: هر ۳ شرط زیر باید به‌طور همزمان و مستقل پاس شده باشند.',
      criterion1: {
        name: 'ورود پول حقیقی در ۳ روز متوالی',
        passed: true,
        note: 'توالی ۳ روز ورود نقدینگی خرد به ارزش کل +۱,۴۸۰ میلیارد تومان',
        dailyFlows: [
          { day: '۲ روز پیش', amount: '+۴۲۰ میلیارد تومان', status: 'positive' },
          { day: 'دیروز', amount: '+۶۱۰ میلیارد تومان', status: 'positive' },
          { day: 'امروز', amount: '+۴۵۰ میلیارد تومان', status: 'positive' },
        ],
      },
      criterion2: {
        name: 'ارزش معاملات خرد بالای میانگین ماهانه',
        passed: true,
        note: '۵۴,۲۰۰ میلیارد تومان (۵۴.۲ همت) در برابر میانگین ماهانه ۱۲ همت (۴.۵ برابر حد نصاب)',
      },
      criterion3: {
        name: 'برتری سرانه خرید حقیقی (قدرت خریدار > ۱)',
        passed: true,
        note: 'سرانه خرید ۸۵ میلیون تومان در برابر سرانه فروش ۴۲ میلیون تومان (نسبت ۱.۸۲ خریدار به فروشنده)',
      },
      isConfirmed: true,
    },
    weightBreakdown: [
      { variable: 'ورود پول حقیقی (توالی ۳ روز)', weight: 30, scoreAchieved: 29, source: 'TSETMC / دیتابورس', evaluation: 'تایید ۳ روز متوالی با حجم مثبت' },
      { variable: 'ارزش معاملات خرد', weight: 20, scoreAchieved: 20, source: 'TSETMC / دیتابورس', evaluation: 'بیشتر از میانگین یک ماه گذشته' },
      { variable: 'قدرت خریدار حقیقی (سرانه خرید/فروش)', weight: 15, scoreAchieved: 15, source: 'دیتابورس / تریدرز آرنا', evaluation: 'نسبت ۱.۸۲ و بزرگتر از ۱' },
      { variable: 'اقتصاد کلان (نرخ بهره، ارز توافقی، کامودیتی)', weight: 20, scoreAchieved: 16, source: 'گزارش‌های رسمی اقتصادی', evaluation: 'گسترش بازار توافقی و ثبات نیما' },
      { variable: 'تحلیل تکنیکال (ابزار زمان‌بندی Timing)', weight: 10, scoreAchieved: 10, source: 'ره‌آورد ۳۶۵ / چارت زنده', evaluation: 'شکست سقف تاریخی با کندل پرقدرت ۶.۳۸ میلیونی' },
      { variable: 'اخبار سیاسی و محیطی', weight: 5, scoreAchieved: 4, source: 'خبرگزاری‌های رسمی معتبر', evaluation: 'آرامش نسبی محیطی' },
    ],
    details: {
      technicalScore: 95,
      fundamentalScore: 88,
      flowScore: 94,
      sentimentScore: 92,
      analysisSummary: 'شاخص کل با شکست سقف تاریخی و ثبت ۶,۳۸۶,۵۷۶ واحد و تایید همزمان ۳ معیار مستقل، در وضعیت سوپربولیش قرار دارد.'
    }
  },
  {
    id: 'gold',
    name: 'طلا و سکه (Gold)',
    nameEn: 'Gold & Coins Market',
    symbol: 'GOLD',
    icon: 'monetization_on',
    score: 92,
    sentiment: 'Strong Bull',
    trafficLight: 'green',
    trafficLightLabel: '🟢 چراغ سبز (۹۲/۱۰۰) - وضعیت بسیار قوی؛ اولویت ۸۰٪ در صندوق‌های شمش (عیار)',
    primaryColor: '#ffb77d',
    metrics: [
      { label: 'انس جهانی طلا:', value: '۴,۶۱۱ دلار (تثبیت سقف)', status: 'positive' },
      { label: 'طلای ۱۸ عیار:', value: '۲۱,۴۱۰,۰۰۰ ت (-۰.۹۷٪)', status: 'positive' },
      { label: 'سکه امامی:', value: '۲۲۱,۹۶۰,۰۰۰ ت (حباب ۳.۲٪)', status: 'positive' },
      { label: 'جریان پول صندوق‌ها:', value: '+۲۴۰ میلیارد ت', status: 'positive' },
    ],
    description: 'کلاس دارایی طلا با کسب امتیاز ۹۲ دارای بالاترین جذابیت است. طبق قانون ستون اصلی طلا، حداقل ۸۰٪ از بخش طلای پورتفو به صندوق‌های شمش‌محور (عیار) اختصاص دارد.',
    threeConfirmations: {
      confirmationTitle: 'قانون تایید سه‌گانه بازار طلا (Gold Triple Confirmation)',
      ruleSummary: 'الزام ورود پله‌ای به صندوق طلای عیار: تایید همزمان ۳ سنسور پیشران طلا.',
      criterion1: {
        name: 'روند صعودی اونس جهانی طلا',
        passed: true,
        note: 'تثبیت بالای ۴۶۱۰ دلار و حمایت بنیادین تقاضای بانک‌های مرکزی جهان',
      },
      criterion2: {
        name: 'جریان پول ورودی به صندوق‌های طلا (عیار)',
        passed: true,
        note: 'توالی ورود پول مثبت به صندوق‌های شمش طلا (+۲۴۰ میلیارد تومان در عیار و کهربا)',
        dailyFlows: [
          { day: '۲ روز پیش', amount: '+۱۸۰ میلیارد تومان', status: 'positive' },
          { day: 'دیروز', amount: '+۲۱۰ میلیارد تومان', status: 'positive' },
          { day: 'امروز', amount: '+۲۴۰ میلیارد تومان', status: 'positive' },
        ],
      },
      criterion3: {
        name: 'جهت حرکت دلار آزاد داخلی و حباب امن',
        passed: true,
        note: 'تثبیت دلار در محدوده ۱۹۹,۵۰۰ تومان با حباب کنترل‌شده ۳.۲٪ سکه',
      },
      isConfirmed: true,
    },
    weightBreakdown: [
      { variable: 'اونس جهانی طلا', weight: 20, scoreAchieved: 19, source: 'تراکت زنده TradingView', evaluation: 'روند تکنیکال و فاندامنتال صعودی پرقدرت' },
      { variable: 'دلار آزاد داخلی', weight: 25, scoreAchieved: 24, source: 'شبکه طلا و ارز (TGJU)', evaluation: 'اهرم دوم رشد طلا در بازار ایران' },
      { variable: 'حباب سکه نسبت به ارزش ذاتی', weight: 20, scoreAchieved: 19, source: 'اتحادیه طلا و جواهر تهران', evaluation: 'حباب در محدوده کم‌ریسک ۳.۲٪' },
      { variable: 'جریان پول صندوق‌های طلا', weight: 15, scoreAchieved: 14, source: 'TSETMC / دیتابورس', evaluation: 'ورود مستمر پول حقیقی به صندوق‌ها' },
      { variable: 'ریسک سیاسی و نظامی', weight: 10, scoreAchieved: 8, source: 'رسانه‌های رسمی و بین‌المللی', evaluation: 'تقاضای مداوم پناهگاه امن' },
      { variable: 'نقدینگی کل کشور', weight: 10, scoreAchieved: 8, source: 'بانک مرکزی جمهوری اسلامی', evaluation: 'روند رشد نقدینگی و پایه پولی' },
    ],
    details: {
      technicalScore: 96,
      fundamentalScore: 94,
      flowScore: 92,
      sentimentScore: 92,
      analysisSummary: 'طبق فرمول دو مرحله‌ای طلا، مرحله ۱ (چراغ سبز با امتیاز ۹۲) تایید است. در مرحله ۲، صندوق عیار به عنوان ابزار اصلی انتخاب شده است.'
    }
  },
  {
    id: 'btc',
    name: 'بیت‌کوین و کریپتو (BTC)',
    nameEn: 'Bitcoin & Crypto',
    symbol: 'BTC',
    icon: 'currency_bitcoin',
    score: 54,
    sentiment: 'Neutral',
    trafficLight: 'red',
    trafficLightLabel: '🔴 چراغ قرمز (۵۴/۱۰۰) - وضعیت نوسانی؛ خرید جدید ممنوع، نگهداری یا تبدیل به طلا/سهام',
    primaryColor: '#ef4444',
    metrics: [
      { label: 'قیمت لحظه‌ای:', value: '۷۷,۲۷۶ دلار (-۰.۰۹٪)', status: 'neutral' },
      { label: 'جریان ETF اسپات:', value: '-۲۸.۵ میلیون $ (خروج)', status: 'negative' },
      { label: 'شاخص ترس و طمع:', value: '۴۸ (خنثی)', status: 'neutral' },
      { label: 'دامیننس بیت‌کوین:', value: '۵۷.۸٪', status: 'neutral' },
    ],
    description: 'امتیاز ۵۴ در محدوده چراغ قرمز (زیر ۶۰) قرار دارد. بر اساس قانون انضباطی S1، خرید جدید در دارایی کریپتو ممنوع بوده و سرمایه به بازارهای با امتیاز بالاتر اختصاص می‌یابد.',
    threeConfirmations: {
      criterion1: { name: 'ورود سرمایه نهادی به ETFها', passed: false, note: 'خروج خفیف نقدینگی ۲۸.۵ میلیون دلاری' },
      criterion2: { name: 'شاخص ترس و طمع (Alternative.me)', passed: false, note: 'سطح ۴۸ خنثی و بدون سیگنال فرصت ترس مفرط' },
      criterion3: { name: 'روند قیمتی و میانگین‌های کلیدی', passed: false, note: 'نوسان زیر مقاومت در کانال ۷۷ هزار دلار' },
      isConfirmed: false,
    },
    weightBreakdown: [
      { variable: 'اقتصاد کلان (DXY و نرخ بهره فدرال)', weight: 30, scoreAchieved: 15, source: 'شاخص DXY / فدرال رزرو', evaluation: 'نقدینگی جهانی تحت تاثیر سیاست‌های پولی' },
      { variable: 'ورود سرمایه به ETFها', weight: 20, scoreAchieved: 9, source: 'CoinGlass / ETF Providers', evaluation: 'خروج سرمایه از صندوق‌های اسپات آمریکا' },
      { variable: 'شاخص ترس و طمع', weight: 15, scoreAchieved: 7, source: 'Alternative.me', evaluation: 'عدم وجود شرایط خرید طمع/ترس مفرط' },
      { variable: 'روند قیمتی (Trend و MAها)', weight: 20, scoreAchieved: 13, source: 'مراجع معتبر تکنیکال', evaluation: 'نوسان در محدوده رنج ۷۷ هزار دلار' },
      { variable: 'قوانین و مقررات', weight: 15, scoreAchieved: 10, source: 'منابع خبری معتبر جهان', evaluation: 'چشم‌انداز نظارتی کمیسیون بورس آمریکا' },
    ],
    details: {
      technicalScore: 60,
      fundamentalScore: 50,
      flowScore: 48,
      sentimentScore: 54,
      analysisSummary: 'چون امتیاز زیر ۶۰ است، خرید جدید کریپتو متوقف و تمرکز روی طلا و سهام است.'
    }
  },
  {
    id: 'usdt',
    name: 'تتر (پارک نقدینگی)',
    nameEn: 'Tether / Cash Park Reserve',
    symbol: 'USDT',
    icon: 'attach_money',
    score: 81,
    sentiment: 'Bullish',
    trafficLight: 'green',
    trafficLightLabel: '🟢 شاخص پارک نقدینگی (۸۱/۱۰۰) - جذابیت بالای حفظ ذخیره نقد/درآمد ثابت',
    primaryColor: '#ffb77d',
    metrics: [
      { label: 'نقش در سیستم S1:', value: 'حفظ قدرت خرید', status: 'positive' },
      { label: 'صندوق جایگزین ریالی:', value: 'افران (۳۰٪ سود)', status: 'positive' },
      { label: 'شاخص اطمینان نقدینگی:', value: 'بسیار بالا', status: 'positive' },
      { label: 'حباب تتر به دلار:', value: 'زیر ۰.۵٪ (نرمال)', status: 'neutral' },
    ],
    description: 'تتر در سیستم S1 به عنوان ابزار نوسان‌گیری دیده نمی‌شود؛ بلکه شاخص جذابیت نگهداری پول نقد در برابر خطرات بازارهاست. نقدینگی آزاد پورتفو در صندوق افران پارک می‌شود.',
    threeConfirmations: {
      criterion1: { name: 'پوشش ریسک و حفظ ارزش ریالی', passed: true, note: 'لنگرگاه ثبات سرمایه در برابر نوسانات تند' },
      criterion2: { name: 'نقدشوندگی سریع آنی T+0', passed: true, note: 'قابلیت تبدیل فوری برای شکار فرصت‌های خرید پله‌ای' },
      criterion3: { name: 'بازدهی روزشمار مکمل در صندوق افران', passed: true, note: 'کسب سود موثر سالانه بالای ۳۰٪ در دوره پارک پول' },
      isConfirmed: true,
    },
    weightBreakdown: [
      { variable: 'جذابیت پارک نقدینگی نسبت به ریسک بازارها', weight: 40, scoreAchieved: 34, source: 'مدل ریاضی مقایسه بازارهای S1', evaluation: 'تامین امنیت و فرصت خرید در اصلاح‌ها' },
      { variable: 'پایداری نرخ و حباب صرافی‌ها', weight: 30, scoreAchieved: 25, source: 'صرافی‌های معتبر رمزارز', evaluation: 'نوسان منطبق با دلار آزاد' },
      { variable: 'نرخ بازده بدون ریسک جایگزین (افران)', weight: 30, scoreAchieved: 22, source: 'صندوق‌های درآمد ثابت بورس', evaluation: 'سود روزشمار مستمر بدون ریسک افت سرمایه' },
    ],
    details: {
      technicalScore: 82,
      fundamentalScore: 80,
      flowScore: 85,
      sentimentScore: 80,
      analysisSummary: 'طبق فلسفه S1، معامله نکردن خود یک تصمیم استراتژیک است. نقدینگی پارک‌شده همواره آماده تبدیل به پله‌های ۲۰ درصدی طلا یا بورس در زمان صدور سیگنال‌های قوی است.'
    }
  },
];

export const initialSignal: SystemS1Signal = {
  actionTitle: 'خرید پله‌ای مجاز است',
  subtitle: 'خروجی سیستم S1',
  confidenceScore: 9, // 9/10
  dataQualityScore: 41, // 41/41
  totalMetricsCount: 41,
  activeMetricsCount: 41,
  summaryText: 'با توجه به ثبات در بازار ارز و ورود جریان نقدینگی خرد به صندوق‌های طلا و درآمد ثابت، شرایط برای انباشت تدریجی دارایی‌های کم‌ریسک فراهم است.',
  allocationSummary: 'تخصیص فعلی: ۴۰٪ درآمد ثابت، ۳۵٪ صندوق طلا، ۲۵٪ سهام. بازتوازن بعدی در انتهای هفته پیش‌بینی می‌شود.',
  recommendedAllocations: {
    fixedIncomePct: 40,
    goldPct: 35,
    equityPct: 25,
    cashPct: 0,
  },
  lastUpdatedJalali: `${getLiveJalaliDateString(0, true)} ${getTehranTimeString(true)}:00`,
  isLive: false,
  overallScore: 81,
};

export const initialSRI: SRIModel = {
  overallScore: 4.4,
  sriScore: 4.4,
  riskLevel: 'moderate',
  riskLevelPersian: 'ریسک متوسط (SRI: ۴.۴ / ۱۰)',
  isEmergencyMode: false,
  tacticalAdjustment: 'پایش دقیق اخبار سیاسی و نرخ بهره بین‌بانکی الزامی است. ورود به موقعیت‌های جدید در پله‌های حداکثر ۲۰ درصدی مجاز است.',
  subIndices: {
    marketRisk: 4.5,
    economicRisk: 5.5,
    politicalRisk: 6.0,
    systematicRisk: 4.0,
    operationalRisk: 2.0,
  },
  warLiquidityPriority: [
    '۱. نقدینگی ریال / تتر (Cash)',
    '۲. طلای فیزیکی ۱۸ عیار / شمش طلا (Physical Gold)',
    '۳. تتر و استیبل‌کوین‌های دلاری (Tether)',
    '۴. دارایی‌های بورس تهران (Bourse Paper Assets)'
  ]
};

export const initialDailyChecklist: DailyChecklistItem[] = [
  {
    id: 'chk-1',
    stepNumber: 1,
    order: 1,
    title: 'دریافت قیمت پایانی واقعی تمام بازارهای چهارگانه و محاسبه درصد تغییرات',
    timeWindow: '۱۷:۰۰ - ۱۷:۱۰',
    isCompleted: true,
    status: 'passed',
    source: 'TSETMC / TGJU / CoinMarketCap',
    sourceReference: 'TSETMC / TGJU / CoinMarketCap / صرافی‌ها',
    description: 'قیمت پایانی بورس، طلای ۱۸، سکه امامی، دلار آزاد، بیت‌کوین و تتر با دقت ثبت و درصد نوسان محاسبه شد.'
  },
  {
    id: 'chk-2',
    stepNumber: 2,
    order: 2,
    title: 'استخراج NAV ابطال واقعی صندوق‌های طلا و سهامی و محاسبه درصد اختلاف (حباب/تخفیف)',
    timeWindow: '۱۷:۱۰ - ۱۷:۱۸',
    isCompleted: true,
    status: 'passed',
    source: 'سامانه بورس کالا / Fipiran',
    sourceReference: 'سامانه مدیریت دارایی بورس کالا / Fipiran',
    description: 'NAV ابطال صندوق عیار، کهربا، طلا، توان و افران بررسی و فیلتر نویز ۲٪ اعمال گردید.'
  },
  {
    id: 'chk-3',
    stepNumber: 3,
    order: 3,
    title: 'پایش و ثبت حجم و ارزش معاملات خرد بورس و برآیند ورود/خروج پول حقیقی',
    timeWindow: '۱۷:۱۸ - ۱۷:۲۵',
    isCompleted: true,
    status: 'passed',
    source: 'دیتابورس / TSETMC',
    sourceReference: 'دیتابورس / TSETMC',
    description: 'ارزش معاملات خرد به ۸.۴۵ همت رسید و ورود پول حقیقی برای سومین روز متوالی مثبت (+۱,۲۴۰ م.ت) ثبت شد.'
  },
  {
    id: 'chk-4',
    stepNumber: 4,
    order: 4,
    title: 'به‌روزرسانی شاخص‌های بازارهای جهانی (اونس طلا، DXY، نفت برنت، بیت‌کوین، ETF Flow)',
    timeWindow: '۱۷:۲۵ - ۱۷:۳۲',
    isCompleted: true,
    status: 'passed',
    source: 'TradingView / CoinGlass',
    sourceReference: 'TradingView / CoinGlass / Alternative.me',
    description: 'اونس طلا در ۲,۷۴۵ دلار صعودی، DXY در ۱۰۳.۸، جریان ETF بیت‌کوین خروج خفیف ۳۵ میلیون دلاری.'
  },
  {
    id: 'chk-5',
    stepNumber: 5,
    order: 5,
    title: 'محاسبه نمره امتیاز ۰ تا ۱۰۰ برای هر یک از ۴ کلاس دارایی',
    timeWindow: '۱۷:۳۲ - ۱۷:۴۰',
    isCompleted: true,
    status: 'passed',
    source: 'موتور محاسباتی فرمول‌های وزنی S1 v1.3',
    sourceReference: 'موتور محاسباتی فرمول‌های وزنی S1 v1.3',
    description: 'بورس: ۸۲ (🟢 سبز) | طلا: ۹۰ (🟢 سبز) | بیت‌کوین: ۵۸ (🔴 قرمز) | تتر پارک نقدینگی: ۸۱ (🟢 سبز).'
  },
  {
    id: 'chk-6',
    stepNumber: 6,
    order: 6,
    title: 'محاسبه شاخص ریسک سیستم (SRI) و بررسی فعال نبودن Emergency Mode',
    timeWindow: '۱۷:۴۰ - ۱۷:۴۵',
    isCompleted: true,
    status: 'passed',
    source: 'ماتریس ۵ گانه ریسک‌های سیستماتیک S1',
    sourceReference: 'ماتریس ۵ گانه ریسک‌های سیستماتیک S1',
    description: 'شاخص SRI عدد ۴.۴ / ۱۰ (ریسک متوسط) محاسبه شد؛ وضعیت اضطراری غیرفعال است.'
  },
  {
    id: 'chk-7',
    stepNumber: 7,
    order: 7,
    title: 'تعیین شاخص اطمینان تصمیم (Decision Confidence Index) بین ۱ تا ۱۰ و بررسی وتو',
    timeWindow: '۱۷:۴۵ - ۱۷:۵۰',
    isCompleted: true,
    status: 'passed',
    source: 'الگوریتم همگرایی داده‌های تکنیکال و فلو',
    sourceReference: 'الگوریتم همگرایی داده‌های تکنیکال، بنیادی و فلو',
    description: 'شاخص اطمینان ۹ از ۱۰ (بسیار بالا)؛ قانون وتوی اطمینان (زیر ۶) غیرفعال بوده و مجوز اقدام صادر شد.'
  },
  {
    id: 'chk-8',
    stepNumber: 8,
    order: 8,
    title: 'اعمال قوانین جابه‌جایی، ورود پله‌ای ۲۰ درصدی و قانون سه تایید',
    timeWindow: '۱۷:۵۰ - ۱۷:۵۴',
    isCompleted: true,
    status: 'passed',
    source: 'فصل ۲ کتاب قانون S1 v1.3',
    sourceReference: 'فصل ۲ کتاب قانون S1 v1.3',
    description: 'قانون ۳ تایید برای طلا و بورس پاس شد. ورود صرفاً در قالب پله ۲۰ درصدی به صندوق عیار تخصیص یافت.'
  },
  {
    id: 'chk-9',
    stepNumber: 9,
    order: 9,
    title: 'به‌روزرسانی ارزش روز، بازدهی و دراودان (Max Drawdown) پورتفوی ۱ میلیارد تومانی',
    timeWindow: '۱۷:۵۴ - ۱۷:۵۷',
    isCompleted: true,
    status: 'passed',
    source: 'پورتفوی کاغذی S1',
    sourceReference: 'موتور پورتفوی فرضی S1 Paper Portfolio',
    description: 'محاسبه و کنترل برخط ارزش روز، بازدهی و دراودان (Max Drawdown) پورتفوی ۱ میلیارد تومانی جهت رعایت سقف ریسک ۱۵٪.'
  },
  {
    id: 'chk-10',
    stepNumber: 10,
    order: 10,
    title: 'ثبت فرضی معاملات تاییدشده با قیمت پایانی واقعی و کسر کارمزد در ژورنال سرمایه‌گذاری',
    timeWindow: '۱۷:۵۷ - ۱۷:۵۹',
    isCompleted: true,
    status: 'passed',
    source: 'دفتر ثبت معاملات رسمی سیستم S1',
    sourceReference: 'دفتر ثبت معاملات رسمی سیستم S1',
    description: 'معاملات با کسر کارمزد دقیق ۰.۱۵٪ بورس کالا و قیمت‌های پایانی تابلو ثبت شدند.'
  },
  {
    id: 'chk-11',
    stepNumber: 11,
    order: 11,
    title: 'صدور رسمی تنها یکی از ۵ خروجی صریح مجاز: خرید / خرید پله‌ای / نگهداری / سیو سود / فروش / عدم اقدام',
    timeWindow: '۱۸:۰۰',
    isCompleted: true,
    status: 'passed',
    source: 'خروجی نهایی سیستم S1',
    sourceReference: 'خروجی نهایی سیستم S1',
    description: 'خروجی نهایی: «خرید پله‌ای مجاز است» (تخصیص به صندوق طلای عیار و درآمد ثابت افران).'
  }
];

export const s1RulebookSections: S1V13RulebookSection[] = [
  {
    id: 's1-sec-1',
    sectionNumber: 'فصل ۱',
    title: 'فلسفه و تعریف سیستم S1',
    subtitle: 'چارچوب فکری، اهداف بنیادین، تعریف موفقیت و اصول ۴ گانه عملیاتی',
    iconName: 'shield',
    paragraphs: [
      {
        heading: '۱-۱. هدف و فلسفه بنیادین سیستم',
        text: 'سیستم S1 یک سیستم معامله‌گری (تریدینگ) نیست؛ بلکه یک سیستم جامع «مدیریت سرمایه و ریسک» است. این سیستم بر پایه ریاضیات و بدون دخالت سوگیری‌های انسانی فعالیت می‌کند.',
        bulletPoints: [
          '۱. حفظ و بقای اصل سرمایه (اولین و مهم‌ترین وظیفه سیستم)',
          '۲. کنترل دقیق و ریاضی ریسک پورتفو',
          '۳. حذف کامل تصمیم‌گیری‌های احساسی، ترس و هیجانات بازار (FOMO & Panic Selling)',
          '۴. دستیابی به بازدهی پایدار و بلندمدت',
          '۵. شکست دادن تورم در افق زمانی بلندمدت'
        ]
      },
      {
        heading: 'اندازه‌گیری به جای پیش‌بینی',
        text: 'سیستم S1 هرگز تلاش نمی‌کند آینده را پیش‌بینی کند، سقف یا کف بازارها را شکار کند، یا بر اساس شایعات و اخبار بدون سند معامله کند. وظیفه سیستم اندازه‌گیری دقیق و ریاضی شرایط فعلی بازارها با داده‌های واقعی و تصمیم‌گیری بر اساس قوانین از پیش تعیین‌شده است.'
      },
      {
        heading: '۱-۲. تعریف موفقیت در سیستم S1',
        text: 'موفقیت در این سیستم با «بیشترین سود ممکن در کوتاه‌مدت» سنجیده نمی‌شود. موفقیت یعنی «کمترین اشتباه بزرگ». کیفیت سیستم بر اساس میزان رعایت انضباط و پایبندی به قوانین سنجیده می‌شود، نه نتیجه عددی تک‌معامله‌ها. حتی اگر تصمیمی به زیان منجر شود، در صورتی که طبق کتاب قانون اتخاذ شده باشد، صحیح تلقی می‌گردد.'
      },
      {
        heading: '۱-۳. اصول چهارگانه عملیاتی سیستم S1',
        text: 'چهار اصل بنیادین زیر خط قرمزهای اجرایی سیستم هستند:',
        bulletPoints: [
          'اصل مقایسه بازارها: هیچ بازاری به خودی خود خوب یا بد نیست. تمام بازارهای بورس، طلا، بیت‌کوین و تتر دائماً مقایسه شده و سرمایه به بالاترین امتیاز نسبی منتقل می‌شود.',
          'اصل عدم اقدام (No Action): اگر داده‌های ورودی ناقص باشند یا سیگنال صریحی صادر نکنند، بهترین تصمیم سرمایه‌گذاری عدم اقدام است. معامله نکردن، خود یک تصمیم استراتژیک است.',
          'اصل شفافیت: تمام امتیازدهی‌ها و جابه‌جایی‌ها باید با داده‌های واقعی و فرمول‌های عددی دقیق قابل توضیح و بازسازی باشند.',
          'اصل نسخه به‌روز (Versioning): قوانین هرگز سلیقه‌ای تغییر نمی‌کنند. اصلاح ساختاری فقط در قالب انتشار نسخه رسمی جدید (مانند v1.3) و پس از تست مجاز است.'
        ]
      }
    ]
  },
  {
    id: 's1-sec-2',
    sectionNumber: 'فصل ۲',
    title: 'مکانیزم و فرمول‌های امتیازدهی (Scoring System)',
    subtitle: 'چراغ‌های سه‌گانه، فرمول‌های ۱۰۰ امتیازی بورس، طلا، بیت‌کوین و قوانین جابه‌جایی',
    iconName: 'sliders',
    paragraphs: [
      {
        heading: '۲-۱. طبقه‌بندی امتیازها و وضعیت چراغ‌ها (۰ تا ۱۰۰)',
        text: 'سیستم S1 هر روز به هر یک از بازارهای اصلی امتیازی بین ۰ تا ۱۰۰ اختصاص می‌دهد:',
        bulletPoints: [
          '🔴 چراغ قرمز (امتیاز ۰ تا ۵۹): وضعیت ضعیف؛ خرید جدید ممنوع، زمان خروج یا کاهش وزن دارایی.',
          '🟡 چراغ زرد (امتیاز ۶۰ تا ۷۹): وضعیت خنثی؛ صرفاً نگهداری (Hold) دارایی‌های موجود، جابه‌جایی ممنوع.',
          '🟢 چراغ سبز (امتیاز ۸۰ تا ۱۰۰): وضعیت بسیار قوی؛ مجاز به خرید جدید یا افزایش وزن دارایی به صورت پله‌ای.'
        ]
      },
      {
        heading: '۲-۲. فرمول و اوزان بورس ایران (۱۰۰ امتیاز)',
        text: 'امتیاز بورس ایران از مجموع معیارهای مستند زیر محاسبه می‌شود:',
        bulletPoints: [
          'ورود پول حقیقی (وزن ۳۰): ورود یک‌روزه معتبر نیست؛ برای تایید باید حداقل ۳ روز متوالی مثبت باشد (منبع: TSETMC/دیتابورس).',
          'ارزش معاملات خرد (وزن ۲۰): باید بیشتر از میانگین یک ماه گذشته باشد تا رونق بازار تایید گردد.',
          'قدرت خریدار حقیقی (وزن ۱۵): نسبت سرانه خرید حقیقی به سرانه فروش حقیقی باید بزرگتر از ۱ باشد.',
          'اقتصاد کلان (وزن ۲۰): ارزیابی نرخ بهره، نرخ ارز توافقی/نیما، سیاست‌های پولی و قیمت کامودیتی‌ها.',
          'تحلیل تکنیکال (وزن ۱۰): صرفاً به عنوان ابزار زمان‌بندی (Timing) استفاده می‌شود، نه تصمیم‌گیری اصلی.',
          'اخبار سیاسی و محیطی (وزن ۵): رصد تنش‌ها یا گشایش‌های موثر بر بازار سهام.'
        ]
      },
      {
        heading: '۲-۳. فرمول و اوزان طلا و سکه (۱۰۰ امتیاز)',
        text: 'امتیاز طلا از مجموع معیارهای زیر محاسبه می‌شود:',
        bulletPoints: [
          'اونس جهانی طلا (وزن ۲۰): سنجش روند تکنیکال و فاندامنتال طلای جهانی در TradingView.',
          'دلار آزاد داخلی (وزن ۲۵): جهت حرکت دلار آزاد به عنوان اهرم دوم رشد طلا در ایران (TGJU).',
          'حباب سکه نسبت به ارزش ذاتی (وزن ۲۰): ارزیابی حباب قیمت و ترجیح صندوق‌های شمش‌محور.',
          'جریان پول صندوق‌های طلا (وزن ۱۵): ورود و خروج پول حقیقی به صندوق‌های طلای بورس کالا.',
          'ریسک سیاسی و نظامی (وزن ۱۰): افزایش ریسک سیاسی مستقیماً تقاضای طلا را ارتقا می‌دهد.',
          'نقدینگی کشور (وزن ۱۰): روند رشد پایه پولی و حجم نقدینگی کل بانک مرکزی.'
        ]
      },
      {
        heading: '۲-۴. فرمول بیت‌کوین و کریپتو (۱۰۰ امتیاز)',
        text: 'امتیاز بیت‌کوین از مجموع متغیرهای زیر محاسبه می‌شود:',
        bulletPoints: [
          'اقتصاد کلان جهانی Macro (وزن ۳۰): شاخص DXY و نرخ بهره فدرال رزرو و نقدینگی جهانی.',
          'ورود سرمایه به ETFها (وزن ۲۰): میزان جریان خرید و فروش صندوق‌های اسپات در آمریکا (CoinGlass).',
          'شاخص ترس و طمع (وزن ۱۵): سنجش احساسات بازار (Alternative.me).',
          'روند قیمتی Trend (وزن ۲۰): میانگین‌های متحرک کلیدی و خطوط روند.',
          'قوانین و مقررات (وزن ۱۵): اخبار نظارتی و مصوبات کمیسیون‌های نظارتی بین‌المللی.'
        ]
      },
      {
        heading: '۲-۵. نقش بازار تتر (پارک نقدینگی)',
        text: 'تتر در سیستم S1 به عنوان ابزار نوسان‌گیری دیده نمی‌شود؛ بلکه شاخص جذابیت نگهداری پول نقد در برابر خطرات بازارهاست. اگر امتیاز بورس، طلا و کریپتو همگی زیر ۶۰ باشند، امتیاز تتر به ۱۰۰ می‌رسد که یعنی تمام سرمایه باید در تتر یا صندوق درآمد ثابت (مانند افران) پارک شود.'
      },
      {
        heading: '۲-۶. شاخص اطمینان تصمیم و قانون وتو',
        text: 'سیستم موظف به محاسبه شاخص اطمینان بین ۱ تا ۱۰ است. ۱ تا ۳ (پایین)، ۴ تا ۶ (متوسط)، ۷ تا ۸ (بالا)، ۹ تا ۱۰ (بسیار بالا). قانون وتو: اگر شاخص اطمینان تصمیم کمتر از ۶ باشد، فرآیند خرید حتی با وجود امتیاز بالای بازار وتو شده و به تعویق می‌افتد.'
      },
      {
        heading: '۲-۷. قوانین جابه‌جایی سرمایه و آستانه‌ها',
        text: 'انضباط اجرایی جابه‌جایی سرمایه بر پایه ۴ قانون قطعی است:',
        bulletPoints: [
          'قانون اختلاف امتیاز: سرمایه تنها در صورت اختلاف حداقل ۱۵ تا ۲۰ امتیاز بین دو بازار منتقل می‌شود. جابه‌جایی برای تفاوت‌های جزئی کاملاً ممنوع است.',
          'قانون سه تایید: برای صدور هر سیگنال، حداقل ۳ معیار مستقل باید همزمان یکدیگر را تایید کنند.',
          'قانون ورود پله‌ای: خریدها در پله‌های حداکثر ۲۰ درصدی از کل سرمایه انجام می‌شوند.',
          'قانون افزایش موقعیت: پله‌های بعدی تنها در صورت حفظ یا ارتقای امتیاز بازار در روزهای بعد مجاز است.'
        ]
      },
      {
        heading: '۲-۸. فرمول دو مرحله‌ای طلا و قانون ستون اصلی (فصل ۶)',
        text: 'تصمیم ورود به طلا و انتخاب ابزار دو تصمیم کاملاً مستقل هستند. مرحله اول: محاسبه امتیاز ۰ تا ۱۰۰ طلا (چراغ سبز بالای ۸۰). مرحله دوم: انتخاب ابزار برتر بر اساس فرمول (اندازه صندوق ۳۰ + نقدشوندگی ۲۰ + اختلاف قیمت با NAV ابطال ۲۰ + ترکیب دارایی شمش ۱۵ + سابقه ۱۵).',
        bulletPoints: [
          'قانون ستون اصلی طلا: حداقل ۸۰٪ از بخش طلای سبد باید در ابزار پایه (صندوق‌های شمشمحور بزرگ مانند عیار) قرار گیرد. ابزارهای نوسانی/سکه حداکثر مجاز به ۲۰٪ هستند.',
          'قانون فیلتر نویز NAV: اختلاف قیمت بازار با NAV ابطال اگر کمتر از ۲ درصد باشد، نویز تلقی شده و معامله بر اساس آن ممنوع است. اختلاف ۲ تا ۵ درصد عادی و بالای ۵ درصد نیازمند واکاوی بنیادی است.'
        ]
      }
    ]
  },
  {
    id: 's1-sec-3',
    sectionNumber: 'فصل ۳',
    title: 'قوانین مدیریت پورتفوی ۱ میلیارد تومانی (S1 Paper Portfolio)',
    subtitle: 'تخصیص دارایی، دفتر ثبت معاملات با کارمزد و قیمت پایانی، مدیریت حد ضرر و سقف دراودان',
    iconName: 'wallet',
    paragraphs: [
      {
        heading: '۳-۱. قوانین تخصیص دارایی‌ها (Asset Allocation)',
        text: 'سقف‌های مجاز تخصیص سرمایه در پورتفوی فرضی ۱ میلیارد تومانی:',
        bulletPoints: [
          'سقف مجاز بورس: حداکثر ۶۰٪ از کل پورتفو (در ۳ پله ۲۰ درصدی مجزا در صورت امتیاز بالای ۸۰).',
          'سقف مجاز طلا: حداکثر ۴۰٪ از کل پورتفو (حداقل ۸۰٪ در عیار شمشمحور).',
          'سقف مجاز بیت‌کوین: حداکثر ۲۰٪ از کل پورتفو.',
          'تتر / درآمد ثابت (پارک پول): نقدینگی باقیمانده همواره در صندوق درآمد ثابت افران یا تتر پارک می‌شود.'
        ]
      },
      {
        heading: '۳-۲. دفتر ثبت معاملات واقعی (Journal Rules)',
        text: 'تمام معاملات باید بر اساس قیمت پایانی واقعی تابلو، کسر کارمزد دقیق بورس/صرافی، ثبت تاریخ، تعداد واحد، ارزش معامله، امتیاز S1 و شاخص اطمینان ثبت شوند. ثبت سند، بخشی از خود معامله است.'
      },
      {
        heading: '۳-۳. مدیریت حد ضرر و حد سود',
        text: 'قوانین خروج و حفظ سرمایه:',
        bulletPoints: [
          'قانون سقف ریسک سبد (Max Drawdown): حداکثر افت مجاز کل پورتفو ۱۵٪ است. در صورت افت بیش از ۱۵٪ از سقف تاریخی، وضعیت هشدار سطح ۱ صادر شده و ورود به پله‌های جدید ممنوع می‌شود.',
          'حد ضرر دارایی‌ها: بر اساس افت امتیاز بازار به زیر ۶۰ فعال می‌شود، نه درصد تکنیکالی.',
          'قانون سیو سود: بر اساس تضعیف متغیرهای اصلی (خروج پول، افت معاملات) رخ می‌دهد، نه درصد سود ثابت.',
          'قانون عدم انتقام (Anti-Revenge): در صورت بسته شدن معامله با زیان، افزایش حجم یا ریسک معامله بعدی برای جبران ضرر اکیداً ممنوع است.'
        ]
      }
    ]
  },
  {
    id: 's1-sec-4',
    sectionNumber: 'فصل ۴',
    title: 'دستورالعمل تحلیل اخبار و ریسک‌های سیستماتیک',
    subtitle: 'طبقه‌بندی ۵گانه ریسک‌ها، فرمول شاخص ریسک سیستم (SRI)، وضعیت اضطراری و شرایط جنگی',
    iconName: 'alert-triangle',
    paragraphs: [
      {
        heading: '۴-۱. طبقه‌بندی پنجگانه ریسک‌ها (A تا E)',
        text: 'پنج حوزه ارزیابی ریسک در سیستم S1:',
        bulletPoints: [
          'ریسک نوع A (ریسک بازار - Market Risk): اصلاح‌های طبیعی قیمت؛ کاهش ملایم امتیاز، خروج کامل نیاز نیست.',
          'ریسک نوع B (ریسک اقتصادی): نرخ بهره بانکی، سیاست‌های شدید انقباضی، رکود اقتصادی، مالیات؛ کاهش تدریجی وزن.',
          'ریسک نوع C (ریسک سیاسی): تحریم‌های جدید، مذاکرات دیپلماتیک، انتخابات؛ کاهش شاخص اطمینان تصمیم.',
          'ریسک نوع D (ریسک سیستماتیک - Systematic Risk): جنگ مستقیم، حملات موشکی، انسداد تنگه هرمز، تعطیلی بورس یا قطعی اینترنت؛ حیاتی‌ترین ریسک سیستم.',
          'ریسک نوع E (ریسک عملیاتی): خرابی هسته بورس، بسته شدن صرافی‌ها، خطای محاسباتی.'
        ]
      },
      {
        heading: '۴-۲. فرمول شاخص ریسک سیستم (System Risk Index - SRI)',
        text: 'سیستم هر روز نمره‌ای بین ۰ تا ۱۰ به هر یک از ۵ ریسک فوق اختصاص داده و شاخص SRI را محاسبه می‌کند:',
        formula: 'SRI = (A + B + C + D + E) / 5',
        bulletPoints: [
          '۰ تا ۳: ریسک پایین؛ بازارها در وضعیت عادی.',
          '۳ تا ۶: ریسک متوسط؛ پایش دقیق اخبار الزامی است.',
          '۶ تا ۸: ریسک بالا؛ کاهش ملایم حجم خرید پله‌ها از ۲۰٪ به ۱۰٪.',
          '۸ تا ۱۰: وضعیت اضطراری (Emergency Mode 🔴).'
        ]
      },
      {
        heading: '۴-۳. پروتکل وضعیت اضطراری (SRI >= 8)',
        text: 'در صورت فراتر رفتن SRI از عدد ۸، خرید دارایی جدید کاملاً ممنوع است، افزایش ریسک سبد ممنوع بوده و سیستم تنها مجاز به حفظ موقعیت‌های فعلی یا کاهش وزن دارایی‌های پرریسک در اولین پنجره معاملاتی است.'
      },
      {
        heading: '۴-۴. شرایط جنگی و زنجیره نقدشوندگی نجات سرمایه',
        text: 'در صورت وقوع جنگ مستقیم یا حملات گسترده، هدف سیستم بقاء و نجات سرمایه است. اولویت بازچیدمان دارایی‌ها:',
        formula: 'Priority: Cash (ریال/تتر) ➔ Physical Gold (طلای فیزیکی) ➔ Tether ➔ Bourse Paper Assets',
        warning: 'در این شرایط، دارایی‌های کاغذی بورس در اولین فرصت نقد شده و به دارایی‌های فیزیکی یا نقد امن تبدیل می‌شوند.'
      },
      {
        heading: '۴-۵. تعطیلی بورس و قطعی داده',
        text: 'در تعطیلی بورس، ثبت معاملات فرضی متوقف شده و قید می‌شود: «بازار تعطیل است؛ تصمیم اجرایی تا بازگشایی به تعویق افتاد». در صورت قطعی اینترنت و نبود داده، حدس زدن ممنوع بوده و خروجی سیستم خودکار به «عدم اقدام (No Action)» تبدیل می‌شود.'
      }
    ]
  },
  {
    id: 's1-sec-5',
    sectionNumber: 'فصل ۵',
    title: 'چک‌لیست روزانه اجرای سیستم S1 (ماده ۱۱)',
    subtitle: '۱۱ گام اجرایی بازبینی روزانه با پایش اتوماتیک ساعت ۲۰:۰۰ و ثبت آخرین پایش دستی زنده',
    iconName: 'check-circle-2',
    paragraphs: [
      {
        heading: 'ماده ۱۱. پروتکل پایش اتوماتیک ساعت ۲۰:۰۰ و اجرای دستی S1',
        text: 'سیستم موظف است هر روز پایش اتوماتیک ساعت ۲۰:۰۰ را اجرا کرده و همواره آخرین پایش دستی زنده را در داشبورد ثبت و نگهداری نماید:',
        bulletPoints: [
          '۱. دریافت قیمت پایانی واقعی تمام بازارهای چهارگانه و محاسبه درصد تغییرات',
          '۲. استخراج NAV ابطال واقعی صندوق‌های طلا و سهامی و محاسبه درصد اختلاف (حباب/تخفیف)',
          '۳. پایش و ثبت حجم و ارزش معاملات خرد بورس و برآیند ورود/خروج پول حقیقی (۳ روز متوالی)',
          '۴. به‌روزرسانی شاخص‌های بازارهای جهانی (اونس طلا، DXY، نفت، بیت‌کوین و ETF Flow)',
          '۵. محاسبه نمره امتیاز ۰ تا ۱۰۰ برای هر یک از کلاس‌های دارایی',
          '۶. محاسبه شاخص ریسک سیستم (SRI) و بررسی فعال نبودن Emergency Mode',
          '۷. تعیین شاخص اطمینان تصمیم (۱ تا ۱۰) و بررسی قانون وتو (زیر ۶)',
          '۸. اعمال قوانین جابه‌جایی، ورود پله‌ای ۲۰ درصدی و قانون سه تایید',
          '۹. به‌روزرسانی ارزش روز، بازدهی و دراودان (Max Drawdown زیر ۱۵٪) پورتفوی ۱ میلیارد تومانی',
          '۱۰. ثبت فرضی معاملات تاییدشده با قیمت پایانی واقعی و کسر کارمزد در ژورنال سرمایه‌گذاری',
          '۱۱. صدور تنها یکی از ۵ خروجی صریح مجاز سیستم'
        ]
      },
      {
        heading: 'خروجی‌های پنج‌گانه صریح و مجاز سیستم S1',
        text: 'خروجی رسمی و نهایی سیستم در هر روز منحصراً باید یکی از موارد زیر باشد:',
        bulletPoints: [
          '🟢 ۱. خرید (Buy)',
          '🟢 ۲. خرید پله‌ای (Staged Buy)',
          '🟡 ۳. نگهداری (Hold)',
          '🟠 ۴. سیو سود (Take Profit)',
          '🔴 ۵. فروش / کاهش موقعیت (Sell)',
          '⚪ ۶. عدم اقدام (No Action)'
        ]
      }
    ]
  }
];

export const initialDailyInputs: InputMetric[] = [
  // Bourse (10 items)
  {
    id: 'tse-overall-index',
    category: 'bourse',
    categoryLabel: 'بورس و سهام',
    title: 'شاخص کل بورس تهران',
    code: 'TSE_OVERALL_INDEX',
    value: '6,386,576',
    unit: 'واحد',
    scoreContribution: 9,
    status: 'bullish',
    weight: 0.20,
    lastUpdated: '12:35',
    description: 'شاخص کل قیمت و بازده نقدی بورس اوراق بهادار تهران',
    source: 'مدیریت فناوری بورس تهران (TSETMC)',
    sourceReference: 'tsetmc.com / شاخص کل',
    timeWindow: '۱۲:۳۰ - ۱۳:۰۰',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'tse-index-change',
    category: 'bourse',
    categoryLabel: 'بورس و سهام',
    title: 'تغییرات شاخص کل',
    code: 'TSE_INDX_PCT',
    value: '+2.61%',
    unit: 'درصد',
    scoreContribution: 9,
    status: 'bullish',
    weight: 0.15,
    lastUpdated: '12:35',
    description: 'تغییرات روزانه شاخص کل بورس تهران (+۱۶۲,۶۹۷ واحد)',
    source: 'TSETMC (مدیریت فناوری بورس تهران)',
    sourceReference: 'tsetmc.com / شاخص کل',
    timeWindow: '۱۲:۳۰ - ۱۳:۰۰',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'tse-retail-volume',
    category: 'bourse',
    categoryLabel: 'بورس و سهام',
    title: 'ارزش معاملات خرد سهام و حق تقدم',
    code: 'TSE_RETAIL_VOL',
    value: '54,200',
    unit: 'میلیارد تومان',
    scoreContribution: 10,
    status: 'bullish',
    weight: 0.20,
    lastUpdated: '13:00',
    description: 'حجم نقدینگی در گردش معاملات خرد بازار (۵۴.۲ همت)',
    source: 'دیتابورس / TSETMC',
    sourceReference: 'databourse.ir / تابلوی معاملات خرد',
    timeWindow: '۱۲:۳۰ - ۱۳:۰۰',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'tse-real-money-flow',
    category: 'bourse',
    categoryLabel: 'بورس و سهام',
    title: 'ورود/خروج پول حقیقی به سهام',
    code: 'TSE_REAL_FLOW',
    value: '+1,480',
    unit: 'میلیارد تومان',
    scoreContribution: 9,
    status: 'bullish',
    weight: 0.20,
    lastUpdated: '13:00',
    description: 'خالص ورود پول سرمایه‌گذاران حقیقی به سهام و صندوق‌های سهامی',
    source: 'TSETMC / بورس‌ویو',
    sourceReference: 'bourseview.ir / برآیند حقیقی',
    timeWindow: '۱۲:۳۰ - ۱۳:۰۰',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'tse-pe-ratio',
    category: 'bourse',
    categoryLabel: 'بورس و سهام',
    title: 'نسبت P/E ttm متوسط بازار',
    code: 'TSE_PE_TTM',
    value: '6.8',
    unit: 'واحد',
    scoreContribution: 8,
    status: 'bullish',
    weight: 0.10,
    lastUpdated: '12:35',
    description: 'نسبت قیمت به سود گذشته‌نگر بازار',
    source: 'Fipiran / سامانه جامع',
    sourceReference: 'fipiran.ir / نسبت‌های مالی بازار',
    timeWindow: '۱۲:۳۰ - ۱۳:۰۰',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'tse-queue-ratio',
    category: 'bourse',
    categoryLabel: 'بورس و سهام',
    title: 'نسبت ارزش صفوف خرید به فروش',
    code: 'TSE_BUY_SELL_QUEUE',
    value: '23.8',
    unit: 'برابر',
    scoreContribution: 9,
    status: 'bullish',
    weight: 0.10,
    lastUpdated: '12:30',
    description: 'برتری قاطع ارزش صفوف تقاضا (۱۴.۸ همت خرید در برابر ۶۲۰ میلیارد فروش)',
    source: 'TSETMC / دیتابورس',
    sourceReference: 'tsetmc.com / صف‌های معاملاتی',
    timeWindow: '۱۲:۳۰ - ۱۳:۰۰',
    verificationStatus: 'DERIVED',
    verificationBadge: '🟡 محاسبه ریاضی',
  },
  {
    id: 'tse-leveraged-premium',
    category: 'bourse',
    categoryLabel: 'بورس و سهام',
    title: 'حباب/پرمیوم صندوق‌های اهرمی',
    code: 'TSE_LEVERAGE_PRM',
    value: '+4.2%',
    unit: 'درصد',
    scoreContribution: 8,
    status: 'bullish',
    weight: 0.08,
    lastUpdated: '12:35',
    description: 'میانگین حباب بازاری صندوق‌های توان، اهرم و شتاب نسبت به NAV',
    source: 'سامانه بورس کالا / Fipiran',
    sourceReference: 'fipiran.com / ابطال اهرمی‌ها',
    timeWindow: '۱۲:۳۰ - ۱۳:۰۰',
    verificationStatus: 'DERIVED',
    verificationBadge: '🟡 فرمول حباب اهرمی',
  },
  {
    id: 'tse-per-capita-power',
    category: 'bourse',
    categoryLabel: 'بورس و سهام',
    title: 'سرانه خرید به فروش حقیقی',
    code: 'TSE_POWER_RATIO',
    value: '1.82',
    unit: 'واحد',
    scoreContribution: 9,
    status: 'bullish',
    weight: 0.07,
    lastUpdated: '12:35',
    description: 'قدرت خریداران حقیقی (۶۴ م.ت خرید در برابر ۳۵ م.ت فروش)',
    source: 'تریدرز آرنا / بورس‌ویو',
    sourceReference: 'tradersarena.ir / سرانه تجمیعی',
    timeWindow: '۱۲:۳۰ - ۱۳:۰۰',
    verificationStatus: 'DERIVED',
    verificationBadge: '🟡 محاسبه سرانه خرید/فروش',
  },
  {
    id: 'tse-fixed-flow-out',
    category: 'bourse',
    categoryLabel: 'بورس و سهام',
    title: 'خروج پول از صندوق‌های درآمد ثابت',
    code: 'TSE_FIXED_DRAIN',
    value: '+420',
    unit: 'میلیارد تومان',
    scoreContribution: 9,
    status: 'bullish',
    weight: 0.05,
    lastUpdated: '13:00',
    description: 'مهاجرت نقدینگی پارک شده به سهام ریسک‌پذیر',
    source: 'TSETMC / دیتابورس',
    sourceReference: 'tsetmc.com / خروج از فیکس‌اینکام',
    timeWindow: '۱۲:۳۰ - ۱۳:۰۰',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },

  // Gold & Coins (9 items)
  {
    id: 'gold-ounce-price',
    category: 'gold',
    categoryLabel: 'طلا و مسکوکات',
    title: 'انس جهانی طلا (XAU/USD)',
    code: 'XAU_USD_GLOBAL',
    value: '4,653',
    unit: 'دلار',
    scoreContribution: 10,
    status: 'bullish',
    weight: 0.25,
    lastUpdated: '17:15',
    description: 'قیمت لحظه‌ای انس جهانی در بازارهای بین‌المللی',
    source: 'TradingView (XAUUSD) / TGJU',
    sourceReference: 'tradingview.com/symbols/XAUUSD',
    timeWindow: '۱۷:۱۵ - ۱۷:۳۰',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'gold-coin-bubble',
    category: 'gold',
    categoryLabel: 'طلا و مسکوکات',
    title: 'حباب سکه تمام طرح جدید',
    code: 'GOLD_COIN_BUBBLE',
    value: '2.1%',
    unit: 'درصد',
    scoreContribution: 9,
    status: 'bullish',
    weight: 0.20,
    lastUpdated: '17:22',
    description: 'درصد حباب قیمتی سکه امامی نسبت به ارزش ذاتی (حباب منصفانه ۲.۱٪)',
    source: 'محاسبه فرمول ذاتی S1 / TGJU',
    sourceReference: 'tgju.org / حباب سکه امامی',
    timeWindow: '۱۷:۲۰ - ۱۷:۳۰',
    verificationStatus: 'DERIVED',
    verificationBadge: '🟡 محاسبه ریاضی',
  },
  {
    id: 'gold-fund-inflow',
    category: 'gold',
    categoryLabel: 'طلا و مسکوکات',
    title: 'ورود پول به صندوق‌های طلای بورس',
    code: 'GOLD_ETF_INFLOW',
    value: '+240',
    unit: 'میلیارد تومان',
    scoreContribution: 9,
    status: 'bullish',
    weight: 0.20,
    lastUpdated: '15:00',
    description: 'جریان نقدینگی ورودی به صندوق‌های عیار، طلا، کهربا و زر',
    source: 'TSETMC / مدیریت بورس کالا',
    sourceReference: 'ime.co.ir / صندوق‌های طلا',
    timeWindow: '۱۵:۰۰ - ۱۵:۳۰',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'gold-18k-gram',
    category: 'gold',
    categoryLabel: 'طلا و مسکوکات',
    title: 'قیمت هر گرم طلای ۱۸ عیار',
    code: 'GOLD_18K_IRR',
    value: '21,677,400',
    unit: 'تومان',
    scoreContribution: 9,
    status: 'bullish',
    weight: 0.15,
    lastUpdated: '17:20',
    description: 'نرخ پایه طلا در بازار سبزه‌میدان و اتحادیه طلا',
    source: 'اتحادیه طلا و جواهر تهران / TGJU',
    sourceReference: 'tgju.org/gold-chart',
    timeWindow: '۱۷:۱۵ - ۱۷:۳۰',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'gold-physical-demand',
    category: 'gold',
    categoryLabel: 'طلا و مسکوکات',
    title: 'شاخص تقاضای آبشده و شمش',
    code: 'GOLD_MELTED_DEMAND',
    value: 'بسیار بالا (High)',
    unit: 'کیفی',
    scoreContribution: 9,
    status: 'bullish',
    weight: 0.10,
    lastUpdated: '17:10',
    description: 'حجم سفارشات بنکداران و شمش‌های ۱ کیلویی بورس کالا',
    source: 'اتحادیه طلا و جواهر تهران',
    sourceReference: 'tgju.org / بازار فیزیکی',
    timeWindow: '۱۷:۰۰ - ۱۷:۱۰',
    verificationStatus: 'DERIVED',
    verificationBadge: '🟡 شاخص ترکیبی',
  },
  {
    id: 'gold-central-bank-auction',
    category: 'gold',
    categoryLabel: 'طلا و مسکوکات',
    title: 'حراج سکه و شمش مرکز مبادله',
    code: 'GOLD_CBI_AUCTION',
    value: 'جذب کامل (100%)',
    unit: 'درصد',
    scoreContribution: 8,
    status: 'bullish',
    weight: 0.10,
    lastUpdated: '09:30',
    description: 'نرخ تخصیص و رقابت متقاضیان در مرکز مبادله ایران',
    source: 'مرکز مبادله ارز و طلای ایران (ICE)',
    sourceReference: 'ice.ir / نتایج حراج شمش و سکه',
    timeWindow: '۱۷:۰۰ - ۱۷:۱۰',
  },

  // Crypto (7 items)
  {
    id: 'btc-price',
    category: 'crypto',
    categoryLabel: 'رمزارزها',
    title: 'قیمت بیت‌کوین (BTC/USDT)',
    code: 'BTC_PRICE_SPOT',
    value: '79,150',
    unit: 'دلار',
    scoreContribution: 6,
    status: 'neutral',
    weight: 0.25,
    lastUpdated: '17:25',
    description: 'قیمت لحظه‌ای بیت‌کوین در صرافی‌های بین‌المللی بایننس / کوین‌بیس',
    source: 'CoinGecko / Binance Live API',
    sourceReference: 'coingecko.com/en/coins/bitcoin',
    timeWindow: '۱۷:۲۵ - ۱۷:۳۲',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'btc-etf-netflow',
    category: 'crypto',
    categoryLabel: 'رمزارزها',
    title: 'خالص جریان ETF‌های اسپات بیت‌کوین',
    code: 'BTC_ETF_FLOW_NET',
    value: '+184.2',
    unit: 'میلیون دلار',
    scoreContribution: 7,
    status: 'bullish',
    weight: 0.20,
    lastUpdated: '17:00',
    description: 'ورود نقدینگی نهادی (Net Inflow) به صندوق‌های اسپات وال‌استریت',
    source: 'CoinGlass / Farside Investors',
    sourceReference: 'coinglass.com/bitcoin-etf',
    timeWindow: '۱۷:۰۰ - ۱۷:۱۵',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'crypto-fear-greed',
    category: 'crypto',
    categoryLabel: 'رمزارزها',
    title: 'شاخص ترس و طمع کریپتو',
    code: 'CRYPTO_FEAR_GREED',
    value: '62',
    unit: 'طمع (0-100)',
    scoreContribution: 6,
    status: 'neutral',
    weight: 0.20,
    lastUpdated: '17:00',
    description: 'احساسات کلی بازار رمزارزها',
    source: 'Alternative.me API',
    sourceReference: 'alternative.me/crypto/fear-and-greed-index',
    timeWindow: '۱۷:۰۰ - ۱۷:۱۵',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'btc-dominance',
    category: 'crypto',
    categoryLabel: 'رمزارزها',
    title: 'دامیننس بیت‌کوین (BTC.D)',
    code: 'BTC_DOMINANCE_PCT',
    value: '58.4%',
    unit: 'درصد',
    scoreContribution: 6,
    status: 'neutral',
    weight: 0.15,
    lastUpdated: '17:10',
    description: 'سهم بازار بیت‌کوین از کل ارزش کریپتو',
    source: 'TradingView (BTC.D)',
    sourceReference: 'tradingview.com/symbols/CRYPTOCAP-BTC.D',
    timeWindow: '۱۷:۱۰ - ۱۷:۲۵',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'crypto-funding-rate',
    category: 'crypto',
    categoryLabel: 'رمزارزها',
    title: 'فاندینگ ریت میانگین صرافی‌ها',
    code: 'CRYPTO_FUNDING_RATE',
    value: '+0.008%',
    unit: 'درصد/۸ساعته',
    scoreContribution: 6,
    status: 'neutral',
    weight: 0.10,
    lastUpdated: '17:00',
    description: 'تعادل قراردادهای آتی اهرمی لانگ و شورت',
    source: 'CoinGlass Funding Dashboard',
    sourceReference: 'coinglass.com/FundingRate',
    timeWindow: '۱۷:۰۰ - ۱۷:۱۵',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'eth-btc-ratio',
    category: 'crypto',
    categoryLabel: 'رمزارزها',
    title: 'نسبت اتریوم به بیت‌کوین (ETH/BTC)',
    code: 'ETH_BTC_PAIR_RATIO',
    value: '0.0331',
    unit: 'نسبت',
    scoreContribution: 5,
    status: 'neutral',
    weight: 0.10,
    lastUpdated: '17:24',
    description: 'قدرت آلت‌کوین‌ها در برابر بیت‌کوین',
    source: 'Binance / TradingView',
    sourceReference: 'tradingview.com/symbols/ETHBTC',
    timeWindow: '۱۷:۲۵ - ۱۷:۳۲',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },

  // Forex & Tether (8 items)
  {
    id: 'usdt-toman-rate',
    category: 'forex',
    categoryLabel: 'ارز و تتر',
    title: 'نرخ تتر به تومان',
    code: 'USDT_TOMAN_RATE',
    value: '199,800',
    unit: 'تومان',
    scoreContribution: 9,
    status: 'bullish',
    weight: 0.30,
    lastUpdated: '17:28',
    description: 'میانگین قیمت تتر در صرافی‌های p2p داخلی (نوبیتکس / والکس)',
    source: 'نوبیتکس / والکس P2P',
    sourceReference: 'nobitex.ir / usdt-irt',
    timeWindow: '۱۷:۲۵ - ۱۷:۳۰',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'usd-free-market',
    category: 'forex',
    categoryLabel: 'ارز و تتر',
    title: 'دلار آزاد تهران (اسکناس)',
    code: 'USD_TEHRAN_CASH',
    value: '200,500',
    unit: 'تومان',
    scoreContribution: 9,
    status: 'bullish',
    weight: 0.25,
    lastUpdated: '17:25',
    description: 'نرخ اعلامی بازار منوچهری و سبزه‌میدان',
    source: 'شبکه اطلاع‌رسانی طلا و ارز (TGJU) / منوچهری',
    sourceReference: 'tgju.org/profile/price_dollar_rl',
    timeWindow: '۱۷:۲۵ - ۱۷:۳۰',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'dirham-herat-arbitrage',
    category: 'forex',
    categoryLabel: 'ارز و تتر',
    title: 'نرخ حواله درهم دبی',
    code: 'AED_TRANSFER_RATE',
    value: '54,500',
    unit: 'تومان',
    scoreContribution: 8,
    status: 'bullish',
    weight: 0.20,
    lastUpdated: '17:15',
    description: 'لیدر اصلی قیمت دلار تهران',
    source: 'شبکه صرافی‌های دبی / TGJU',
    sourceReference: 'tgju.org/profile/price_aed',
    timeWindow: '۱۷:۱۵ - ۱۷:۳۰',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'nima-exchange-rate',
    category: 'forex',
    categoryLabel: 'ارز و تتر',
    title: 'نرخ دلار نیما / مبادله‌ای',
    code: 'NIMA_COMMERCIAL_RATE',
    value: '138,450',
    unit: 'تومان',
    scoreContribution: 7,
    status: 'bullish',
    weight: 0.15,
    lastUpdated: '16:45',
    description: 'نرخ تسعیر واردات و شرکت‌های صادراتی بورس',
    source: 'مرکز مبادله ارز و طلای ایران (ICE)',
    sourceReference: 'ice.ir / سامانه نیما',
    timeWindow: '۱۶:۳۰ - ۱۷:۰۰',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'usdt-bubble-ratio',
    category: 'forex',
    categoryLabel: 'ارز و تتر',
    title: 'حباب تتر نسبت به دلار فیزیکی',
    code: 'USDT_BUBBLE_PREMIUM',
    value: '-700',
    unit: 'تومان',
    scoreContribution: 7,
    status: 'bullish',
    weight: 0.10,
    lastUpdated: '17:28',
    description: 'تخفیف تتر رمزارزی نسبت به اسکناس فیزیکی',
    source: 'محاسبه ریاضی S1 (تتر منهای اسکناس)',
    sourceReference: 'nobitex.ir / مقایسه با اسکناس',
    timeWindow: '۱۷:۲۵ - ۱۷:۳۰',
    verificationStatus: 'DERIVED',
    verificationBadge: '🟡 محاسبه ریاضی',
  },

  // Macro & Global Indicators (8 items)
  {
    id: 'global-dxy-index',
    category: 'macro',
    categoryLabel: 'کلان و بازارهای جهانی',
    title: 'شاخص دلار آمریکا (DXY)',
    code: 'DXY_INDEX_GLOBAL',
    value: '101.20',
    unit: 'واحد',
    scoreContribution: 7,
    status: 'neutral',
    weight: 0.20,
    lastUpdated: '17:10',
    description: 'قدرت نسبی دلار در برابر سبد ۶ ارز معتبر جهانی',
    source: 'TradingView (DXY)',
    sourceReference: 'tradingview.com/symbols/TVC-DXY',
    timeWindow: '۱۷:۱۰ - ۱۷:۲۵',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'global-brent-oil',
    category: 'macro',
    categoryLabel: 'کلان و بازارهای جهانی',
    title: 'نفت خام برنت (Brent Oil)',
    code: 'BRENT_OIL_USD',
    value: '86.95',
    unit: 'دلار',
    scoreContribution: 7,
    status: 'bullish',
    weight: 0.20,
    lastUpdated: '17:05',
    description: 'قیمت هر بشکه نفت برنت دریای شمال',
    source: 'TradingView (UKOIL) / TGJU',
    sourceReference: 'tradingview.com/symbols/TVC-UKOIL',
    timeWindow: '۱۷:۰۵ - ۱۷:۲۵',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'global-vix-index',
    category: 'macro',
    categoryLabel: 'کلان و بازارهای جهانی',
    title: 'شاخص نوسان و ترس وال‌استریت (VIX)',
    code: 'VIX_VOLATILITY_INDEX',
    value: '14.2',
    unit: 'واحد',
    scoreContribution: 8,
    status: 'bullish',
    weight: 0.15,
    lastUpdated: '17:10',
    description: 'شاخص نوسانات بازار سهام آمریکا',
    source: 'CBOE / TradingView',
    sourceReference: 'cboe.com/vix',
    timeWindow: '۱۷:۱۰ - ۱۷:۲۵',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'interbank-interest-rate',
    category: 'macro',
    categoryLabel: 'کلان و بازارهای جهانی',
    title: 'نرخ سود بازار بین‌بانکی',
    code: 'INTERBANK_RATE_CBI',
    value: '23.85%',
    unit: 'درصد سالانه',
    scoreContribution: 7,
    status: 'neutral',
    weight: 0.25,
    lastUpdated: '08:30',
    description: 'هزینه استقراض شبانه بانک‌ها نزد بانک مرکزی',
    source: 'بانک مرکزی جمهوری اسلامی ایران (CBI)',
    sourceReference: 'cbi.ir / بازار بین‌بانکی',
    timeWindow: 'گزارش هفتگی رسمی',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'repo-interest-rate',
    category: 'macro',
    categoryLabel: 'کلان و بازارهای جهانی',
    title: 'نرخ توافق بازخرید (ریپو)',
    code: 'REPO_RATE_CBI',
    value: '23.0%',
    unit: 'درصد',
    scoreContribution: 7,
    status: 'neutral',
    weight: 0.20,
    lastUpdated: '08:30',
    description: 'عملیات بازار باز هفتگی بانک مرکزی',
    source: 'بانک مرکزی جمهوری اسلامی ایران (CBI)',
    sourceReference: 'cbi.ir / عملیات بازار باز',
    timeWindow: 'گزارش هفتگی رسمی',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'm2-money-growth',
    category: 'macro',
    categoryLabel: 'کلان و بازارهای جهانی',
    title: 'رشد سالانه نقدینگی (M2)',
    code: 'M2_ANNUAL_GROWTH',
    value: '28.4%',
    unit: 'درصد',
    scoreContribution: 8,
    status: 'bullish',
    weight: 0.20,
    lastUpdated: '08:00',
    description: 'موتور سوخت تورمی و محرک رشد دارایی‌ها',
    source: 'بانک مرکزی CBI / گزارش ماهانه',
    sourceReference: 'cbi.ir / نماگرهای اقتصادی',
    timeWindow: 'گزارش ماهانه رسمی',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
  {
    id: 'treasury-yield-ybond',
    category: 'macro',
    categoryLabel: 'کلان و بازارهای جهانی',
    title: 'بازده اسناد خزانه اسلامی (اخزا)',
    code: 'YTM_EBR_BONDS',
    value: '31.4%',
    unit: 'YTM موثر',
    scoreContribution: 6,
    status: 'neutral',
    weight: 0.15,
    lastUpdated: '15:00',
    description: 'نرخ بهره بدون ریسک اوراق دولتی در بورس',
    source: 'فرابورس ایران (IFB) / Fipiran',
    sourceReference: 'ifb.ir / اسناد خزانه اسلامی',
    timeWindow: '۱۵:۰۰ - ۱۵:۳۰',
    verificationStatus: 'VERIFIED',
    verificationBadge: '🟢 تأییدشده رسمی',
  },
];

export const initialFunds: FundItem[] = [
  // 1. Fixed Income: AFRAN (لنگرگاه نقدینگی)
  {
    id: 'fund-afran',
    name: 'صندوق با درآمد ثابت افران',
    type: 'fixed_income',
    typeLabel: 'درآمد ثابت (پارک نقدینگی)',
    ticker: 'افران',
    currentAllocationPct: 80,
    recommendedAllocationPct: 100,
    navPerUnit: 52761,
    monthlyReturn: 2.55,
    quarterlyReturn: 7.85,
    aumBillionToman: 28000,
    riskRating: 'low'
  },

  // 2. Gold Fund: AYAR (پوشش تورم)
  {
    id: 'fund-ayar',
    name: 'صندوق شمش طلای عیار مفید',
    type: 'gold',
    typeLabel: 'صندوق شمش طلا (پوشش تورم)',
    ticker: 'عیار',
    currentAllocationPct: 20,
    recommendedAllocationPct: 20,
    navPerUnit: 58455,
    monthlyReturn: 9.4,
    quarterlyReturn: 26.2,
    aumBillionToman: 26500,
    riskRating: 'medium'
  },

  // 3. Leveraged Fund: TAVAN (شتاب‌دهنده بورس)
  {
    id: 'fund-tavan',
    name: 'صندوق اهرمی توان مفید',
    type: 'leveraged',
    typeLabel: 'اهرمی بورس (شتاب‌دهنده)',
    ticker: 'توان',
    currentAllocationPct: 0,
    recommendedAllocationPct: 0,
    navPerUnit: 24800,
    monthlyReturn: 12.8,
    quarterlyReturn: 28.5,
    aumBillionToman: 4300,
    riskRating: 'very_high'
  },

  // 4. Crypto: BITCOIN (بیت‌کوین)
  {
    id: 'asset-btc',
    name: 'بیت‌کوین (Bitcoin - BTC)',
    type: 'crypto',
    typeLabel: 'رمزارز و بازار بین‌المللی',
    ticker: 'BTC',
    currentAllocationPct: 0,
    recommendedAllocationPct: 0,
    navPerUnit: 64200,
    monthlyReturn: 8.2,
    quarterlyReturn: 19.5,
    aumBillionToman: 1200000,
    riskRating: 'high'
  },

  // 5. Equity Fund: KHABARGAN (صندوق سهامی خبرگان)
  {
    id: 'fund-khabargan',
    name: 'صندوق سهامی خبرگان نفت و گاز',
    type: 'equity',
    typeLabel: 'سهامی شاخص‌ساز بورس (آلفا)',
    ticker: 'خبرگان',
    currentAllocationPct: 0,
    recommendedAllocationPct: 0,
    navPerUnit: 34200,
    monthlyReturn: 7.6,
    quarterlyReturn: 16.4,
    aumBillionToman: 6100,
    riskRating: 'high'
  }
];

export const initialTelegramConfig: TelegramConfig = {
  botToken: '',
  channelId: '@SystemS1_Signals',
  channelName: 'کانال سیگنال و بازتوازن S1',
  autoSendEnabled: false,
  autoSendTime: '10:30',
  includeGauges: true,
  includeAllocations: true,
  lastSentTimestamp: `${getLiveJalaliDateString(0, true)} ${getTehranTimeString(true)}:15`
};

export const initialHistoryLogs: SystemHistoryLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-08-21 17:00:00',
    jalaliDate: `${getLiveJalaliDateString(0, true)} 17:00`,
    action: 'خرید پله‌ای مجاز است',
    compositeScore: 81,
    bourseScore: 82,
    goldScore: 90,
    btcScore: 58,
    usdtScore: 81,
    confidence: '۹/۱۰ (بسیار بالا)',
    notes: 'تثبیت نقدینگی خرد در صندوق‌های طلا و درآمد ثابت، کاهش ریسک خروج نقدینگی'
  },
  {
    id: 'log-2',
    timestamp: '2026-08-20 17:00:00',
    jalaliDate: `${getLiveJalaliDateString(-1, true)} 17:00`,
    action: 'صبر و نظاره (Hold)',
    compositeScore: 68,
    bourseScore: 65,
    goldScore: 86,
    btcScore: 52,
    usdtScore: 74,
    confidence: '۸/۱۰ (بالا)',
    notes: 'نوسانات نرخ بهره بین‌بانکی و اصلاح موقت شاخص کل'
  },
  {
    id: 'log-3',
    timestamp: '2026-08-19 17:00:00',
    jalaliDate: `${getLiveJalaliDateString(-2, true)} 17:00`,
    action: 'تثبیت سود و افزایش نقدینگی',
    compositeScore: 55,
    bourseScore: 50,
    goldScore: 78,
    btcScore: 48,
    usdtScore: 70,
    confidence: '۸.۵/۱۰',
    notes: 'افزایش حباب سکه به بالای ۲۴٪ و لزوم شناسایی سود در اهرمی‌ها'
  }
];

// ====================================================
// ۱. پورتفوی کاغذی ۱ میلیارد تومانی (Paper Portfolio 1B Toman)
// بر مبنای ۴ کلاس دارایی مصوب سیستم S1:
// ۱. صندوق درآمد ثابت افران (پارک اتوماتیک نقدینگی و سود روزشمار)
// ۲. صندوق طلای عیار (خرید پله‌ای با قیمت پایانی روز معاملاتی بعد)
// ۳. صندوق سهامی خبرگان (خرید پله‌ای با قیمت پایانی روز معاملاتی بعد)
// ۴. بیت‌کوین (BTC) (خرید با سیگنال کریپتو، معامله لحظه‌ای و آنی ۲۴/۷)
// ====================================================

export const initialPortfolioSummary: PortfolioSummary = {
  initialCapitalToman: 1_000_000_000, // 1 Billion Toman Starting Capital
  currentValueToman: 1_000_000_000,
  dailyPnlToman: 0,
  dailyPnlPct: 0.0,
  totalPnlToman: 0,
  totalPnlPct: 0.0,
  maxDrawdownPct: 0.0,
  winRatePct: 100.0,
  sharpeRatio: 0.0,
  cashBalanceToman: 0, // تمام پول آزاد به صورت اتوماتیک در افران پارک می‌شود
  fixedIncomeParkToman: 1_000_000_000,
  investedValueToman: 1_000_000_000,
  lastRebalanceDateJalali: getLiveJalaliDateString(0, true),
  activePositionsCount: 1, // افران (پارک نقدینگی)
  pendingOrdersCount: 1, // سفارش در انتظار خرید پله‌ای عیار فردا
};

export const initialPortfolioAssets: PortfolioAssetItem[] = [
  {
    id: 'asset-afran',
    name: 'صندوق درآمد ثابت افران (پارک نقدینگی)',
    ticker: 'افران (Afran)',
    category: 'fixed_income',
    categoryLabel: 'درآمد ثابت / سود روزشمار',
    allocatedValueToman: 1_000_000_000,
    initialCostToman: 1_000_000_000,
    weightPct: 100.0,
    allocationStatusLabel: 'پارک ۱۰۰٪ سرمایه آزاد (سود روزشمار)',
    unitsCount: 884955,
    avgBuyPriceToman: 1130,
    currentPriceToman: 1130,
    pnlToman: 0,
    pnlPct: 0.0,
    dailyChangePct: 0.08,
    status: 'neutral',
    color: '#10b981',
    executionRule: 'next_day_close',
    description: 'پارک خودکار ۱۰۰٪ سرمایه آزاد سبد در غیاب سیگنال تاییدشده جهت حفظ ارزش اصل پول و دریافت سود روزشمار موثر ۳۰٪+',
  },
  {
    id: 'asset-ayar',
    name: 'صندوق سرمایه‌گذاری طلای عیار',
    ticker: 'عیار (Ayar)',
    category: 'gold_etf',
    categoryLabel: 'صندوق طلای بورس کالا',
    allocatedValueToman: 0,
    initialCostToman: 0,
    weightPct: 0.0,
    allocationStatusLabel: 'آماده خرید پله‌ای بر اساس سیگنال معتبر طلا',
    unitsCount: 0,
    avgBuyPriceToman: 0,
    currentPriceToman: 17200,
    pnlToman: 0,
    pnlPct: 0.0,
    dailyChangePct: 0.0,
    status: 'neutral',
    color: '#ffb77d',
    executionRule: 'next_day_close',
    description: 'تخصیص پله‌ای پویا متناسب با امتیاز طلا (نمره بالای ۷۵)؛ اجرای معامله بر مبنای قیمت پایانی روز کاری بعد با کسر از افران',
  },
  {
    id: 'asset-khabargan',
    name: 'صندوق سهامی خبرگان',
    ticker: 'خبرگان (Khabargan)',
    category: 'equity_etf',
    categoryLabel: 'صندوق سرمایه‌گذاری سهامی',
    allocatedValueToman: 0,
    initialCostToman: 0,
    weightPct: 0.0,
    allocationStatusLabel: 'پایش مستمر جریان نقدینگی و ورود خرد',
    unitsCount: 0,
    avgBuyPriceToman: 0,
    currentPriceToman: 2450,
    pnlToman: 0,
    pnlPct: 0.0,
    dailyChangePct: 0.0,
    status: 'neutral',
    color: '#ec4899',
    executionRule: 'next_day_close',
    description: 'تخصیص پله‌ای در صورت تایید شرایط بورس تهران؛ اجرای معامله بر مبنای قیمت پایانی روز کاری بعد با کسر از افران',
  },
  {
    id: 'asset-tavan',
    name: 'صندوق اهرمی توان',
    ticker: 'توان (Tavan)',
    category: 'equity_etf',
    categoryLabel: 'صندوق اهرمی بورس (شتاب‌دهنده)',
    allocatedValueToman: 0,
    initialCostToman: 0,
    weightPct: 0.0,
    allocationStatusLabel: 'آماده ورود در روندهای پرقدرت صعودی بورس',
    unitsCount: 0,
    avgBuyPriceToman: 0,
    currentPriceToman: 2480,
    pnlToman: 0,
    pnlPct: 0.0,
    dailyChangePct: 0.0,
    status: 'neutral',
    color: '#f59e0b',
    executionRule: 'next_day_close',
    description: 'شتاب‌دهنده بازدهی سبد در روندهای صعودی بورس مشروط به تایید کامل نمره بورس و ورود پول حقیقی',
  },
  {
    id: 'asset-btc',
    name: 'بیت‌کوین (Bitcoin - BTC)',
    ticker: 'BTC (بیت‌کوین)',
    category: 'crypto',
    categoryLabel: 'کریپتو و بازار جهانی',
    allocatedValueToman: 0,
    initialCostToman: 0,
    weightPct: 0.0,
    allocationStatusLabel: 'عدم اقدام (نمره زیر ۶۰)',
    unitsCount: 0,
    avgBuyPriceToman: 0,
    currentPriceToman: 77250,
    pnlToman: 0,
    pnlPct: 0.0,
    dailyChangePct: 0.0,
    status: 'neutral',
    color: '#f59e0b',
    executionRule: 'instant',
    description: 'تخصیص پله‌ای در صورت عبور نمره از ۶۰ و صدور مجوز ورود ۲۴/۷ با معامله آنی',
  },
];

export const initialPortfolioPendingOrders: PortfolioPendingOrder[] = [
  {
    id: 'po-1',
    createdAtJalali: `${getLiveJalaliDateString(0, true)} ۱۷:۳۰`,
    assetId: 'asset-ayar',
    assetName: 'صندوق طلای عیار',
    assetTicker: 'عیار',
    orderType: 'staged_buy',
    sourceAssetTicker: 'افران (پارک نقدینگی)',
    targetAllocationPct: 20.0,
    amountToman: 200_000_000,
    estimatedPriceToman: 17200,
    estimatedUnits: 11627,
    executionRule: 'next_day_close',
    executionTimingLabel: 'قیمت پایانی روز کاری بعد (فردا)',
    scheduledExecutionDateJalali: `فردا (اولین روز کاری معاملاتی بعد)`,
    status: 'pending',
    signalTriggerReason: 'صدور سیگنال خرید پله‌ای طلا (چراغ سبز با امتیاز ۹۰ و تایید ۳گانه) - پله ۲۰ درصدی',
  },
];

export const initialPortfolioHistory: PortfolioHistoryPoint[] = [
  {
    dateJalali: getLiveJalaliDateString(0, true),
    dateKey: 'روز اول',
    portfolioValue: 1_000_000_000,
    portfolioValueMillion: 1000.0,
    drawdownPct: 0.0,
    dailyReturnPct: 0.0,
    benchmarkValueMillion: 1000.0,
    signalAction: 'افتتاح پورتفو',
    notes: 'افتتاح پورتفوی کاغذی ۱ میلیارد تومانی و پارک ۱۰۰٪ سرمایه در صندوق درآمد ثابت افران'
  },
];

export const initialPortfolioTrades: PortfolioTradeItem[] = [
  {
    id: 'tr-0',
    dateJalali: `${getLiveJalaliDateString(0, true)} ۰۹:۰۰`,
    assetTicker: 'افران',
    assetName: 'صندوق درآمد ثابت افران',
    type: 'rebalance',
    amountToman: 1_000_000_000,
    units: 884955,
    unitPriceToman: 1130,
    rationale: 'افتتاح و پارک اتوماتیک ۱۰۰٪ نقدینگی آزاد پورتفو در صندوق افران جهت کسب سود روزشمار',
    executionMode: 'next_day_close',
  },
];

// ====================================================
// ۲. اخبار، ریسک‌های سیستماتیک و تحلیل هوش مصنوعی (News & Systemic Risks)
// ====================================================

export const initialNews: NewsItem[] = [
  // دسته اول: مهمترین اخبار اقتصاد ایران و جهان
  {
    id: 'news-1',
    category: 'iran_global',
    categoryLabel: 'اقتصاد ایران و جهان',
    title: 'تثبیت نرخ بهره فدرال رزرو و سیگنال کاهش در نشست آتی FOMC',
    source: 'بلومبرگ / وال‌استریت ژورنال',
    timeJalali: '۲۵ دقیقه پیش',
    importance: 'critical',
    sentiment: 'bullish',
    summary: 'جروم پاول اعلام کرد کنترل تورم به سمت تارگت ۲ درصدی نزدیک شده و احتمال آغاز چرخه انبساط پولی وجود دارد.',
    impactAnalysis: 'کاهش شاخص DXY و جهش تقاضا در کامودیتی‌ها و انس جهانی طلا به نفع دارایی‌های ضدتورمی ایران.',
    affectedMarkets: ['طلای جهانی', 'بیت‌کوین', 'کامودیتی'],
    tags: ['فدرال رزرو', 'نرخ بهره', 'انس جهانی'],
  },
  {
    id: 'news-2',
    category: 'iran_global',
    categoryLabel: 'اقتصاد ایران و جهان',
    title: 'تصویب کلیات لایحه بودجه با رویکرد واقعی‌سازی نرخ ارز ترجیحی',
    source: 'خبرگزاری ایسنا / سنا',
    timeJalali: '۱ ساعت پیش',
    importance: 'high',
    sentiment: 'bullish',
    summary: 'مجلس شورای اسلامی بر کاهش رانت ارز ترجیحی و همگرایی نرخ نیما با بازار توافقی تأکید کرد.',
    impactAnalysis: 'افزایش مستقیم سودآوری شرکت‌های پتروشیمی، فلزی و معدنی در بازار بورس تهران.',
    affectedMarkets: ['بورس تهران', 'صندوق‌های سهامی'],
    tags: ['بودجه', 'ارز نیما', 'پتروشیمی'],
  },
  {
    id: 'news-3',
    category: 'iran_global',
    categoryLabel: 'اقتصاد ایران و جهان',
    title: 'افزایش ذخایر استراتژیک طلای بانک‌های مرکزی جهان در ۳ ماهه اخیر',
    source: 'شورای جهانی طلا (WGC)',
    timeJalali: '۳ ساعت پیش',
    importance: 'medium',
    sentiment: 'bullish',
    summary: 'بانک‌های مرکزی چین، لهستان و هند خرید طلا را با حجم بی‌سابقه در ماه جاری تداوم بخشیدند.',
    impactAnalysis: 'ایجاد کف قیمتی بسیار مستحکم بالای ۲۶۵۰ دلار برای انس طلا.',
    affectedMarkets: ['طلا و مسکوکات', 'صندوق‌های طلا'],
    tags: ['بانک مرکزی چین', 'طلا'],
  },

  // دسته دوم: اخبار بازار کریپتو و بورس تهران
  {
    id: 'news-4',
    category: 'crypto_bourse',
    categoryLabel: 'کریپتو و بورس تهران',
    title: 'ورود پول حقیقی بیش از ۶۸۰ میلیارد تومانی به سهام شاخص‌ساز و صندوق‌های اهرمی',
    source: 'مدیریت فناوری بورس تهران (TSETMC)',
    timeJalali: '۴۰ دقیقه پیش',
    importance: 'critical',
    sentiment: 'bullish',
    summary: 'ارزش معاملات خرد به بالای ۸.۲ همت رسید و سرانه خرید حقیقی به ۲۸ میلیون تومان در مقابل ۱۸ میلیون فروشنده ثبت شد.',
    impactAnalysis: 'تأیید مومنتوم صعودی کوتاه‌مدت و ورود به فاز انباشت در صندوق‌های توان، اهرم و فیروزه.',
    affectedMarkets: ['بورس تهران', 'صندوق اهرمی'],
    tags: ['ارزش معاملات', 'پول هوشمند', 'شاخص کل'],
  },
  {
    id: 'news-5',
    category: 'crypto_bourse',
    categoryLabel: 'کریپتو و بورس تهران',
    title: 'ثبت ورود خالص سرمایه به ETFهای اسپات بیت‌کوین بلک‌راک پس از ۴ روز اصلاح',
    source: 'Coindesk / Glassnode',
    timeJalali: '۲ ساعت پیش',
    importance: 'high',
    sentiment: 'neutral',
    summary: 'بیش از ۳۱۰ میلیون دلار سرمایه جدید به IBIT بلک‌راک و فیدلیتی واریز گردید و ذخایر صرافی‌ها کاهش یافت.',
    impactAnalysis: 'تثبیت بیت‌کوین در حمایت داینامیک و کاهش احتمال ریزش سنگین به زیر کف‌های کلیدی.',
    affectedMarkets: ['بیت‌کوین', 'تتر'],
    tags: ['بیت‌کوین', 'BlackRock ETF', 'آنچین'],
  },
  {
    id: 'news-6',
    category: 'crypto_bourse',
    categoryLabel: 'کریپتو و بورس تهران',
    title: 'ترافیک سنگین صدور واحدهای صندوق‌های طلای بورس کالا',
    source: 'بورس کالای ایران',
    timeJalali: '۴ ساعت پیش',
    importance: 'medium',
    sentiment: 'bullish',
    summary: 'حجم معاملات صندوق‌های طلا (عیار، طلا، کهربا) از مرز ۱,۴۰۰ میلیارد تومان در یک روز فراتر رفت.',
    impactAnalysis: 'تمایل قوی سرمایه‌گذاران به پوشش ریسک‌های تورمی با استفاده از ابزارهای بورس کالا.',
    affectedMarkets: ['صندوق‌های طلا', 'گواهی سپرده سکه'],
    tags: ['صندوق عیار', 'بورس کالا'],
  },

  // دسته سوم: تصمیمات بانک مرکزی و سازمان بورس
  {
    id: 'news-7',
    category: 'cbi_seo',
    categoryLabel: 'بانک مرکزی و سازمان بورس',
    title: 'دستورالعمل جدید بانک مرکزی برای بازار توافقی ارز و تسهیل تسویه ارزی صادرکنندگان',
    source: 'روابط عمومی بانک مرکزی (CBI)',
    timeJalali: '۵۰ دقیقه پیش',
    importance: 'critical',
    sentiment: 'bullish',
    summary: 'امکان خرید و فروش مستقیم ارز توافقی با حاشیه سود رقابتی جهت کاهش انگیزه نگهداری ارز در خارج.',
    impactAnalysis: 'کاهش شکاف دلار آزاد و نیما و شفافیت در شناسایی سود تسعیر ارز بانک‌ها و شرکت‌های صادرات‌محور.',
    affectedMarkets: ['دلار نیما', 'گروه بانکی', 'پتروشیمی'],
    tags: ['ارز توافقی', 'بانک مرکزی', 'فرزین'],
  },
  {
    id: 'news-8',
    category: 'cbi_seo',
    categoryLabel: 'بانک مرکزی و سازمان بورس',
    title: 'ابلاغیه سازمان بورس در خصوص افزایش سقف سرمایه‌گذاری صندوق‌های با درآمد ثابت در سهام',
    source: 'پایگاه اطلاع‌رسانی سنا (SEO)',
    timeJalali: '۲ ساعت پیش',
    importance: 'high',
    sentiment: 'bullish',
    summary: 'سقف سرمایه‌گذاری صندوق‌های فیکس اینکام در سهام و حق تقدم تا ۱۵ درصد افزایش یافت.',
    impactAnalysis: 'تزریق پتانسیل بیش از ۲۰ هزار میلیارد تومان نقدینگی تازه به بازار سرمایه در ماه‌های آینده.',
    affectedMarkets: ['بورس تهران', 'صندوق‌های درآمد ثابت'],
    tags: ['سازمان بورس', 'صندوق درآمد ثابت', 'نقدینگی'],
  },
  {
    id: 'news-9',
    category: 'cbi_seo',
    categoryLabel: 'بانک مرکزی و سازمان بورس',
    title: 'کنترل نرخ بهره بین‌بانکی در کانال ۲۳.۷ درصد با عملیات ریپو هدفمند',
    source: 'معاونت اقتصادی بانک مرکزی',
    timeJalali: '۵ ساعت پیش',
    importance: 'medium',
    sentiment: 'neutral',
    summary: 'بانک مرکزی با تزریق ۱۱۰ همت در بازار بین‌بانکی مانع از جهش نرخ بهره بدون ریسک شد.',
    impactAnalysis: 'جلوگیری از خروج پول از بازارهای ریسکی به سمت سپرده‌های منجمد بانکی.',
    affectedMarkets: ['صندوق با درآمد ثابت افران', 'بازار بدهی'],
    tags: ['ریپو', 'نرخ بهره بین‌بانکی'],
  },

  // دسته چهارم: وضعیت ریسک‌های سیاسی و نظامی
  {
    id: 'news-10',
    category: 'geopolitical',
    categoryLabel: 'ریسک‌های سیاسی و نظامی',
    title: 'گزارش ارزیابی نهادهای دیپلماتیک از تحولات منطقه‌ای و تداوم رایزنی‌های غیرمستقیم',
    source: 'شورای امنیت / رویترز خاورمیانه',
    timeJalali: '۱ ساعت پیش',
    importance: 'high',
    sentiment: 'neutral',
    summary: 'سیگنال‌های دیپلماتیک حاکی از مدیریت تنش‌ها در دالان‌های بین‌المللی است، اما سطح آماده‌باش دفاعی در سطح متوسط نگهداری می‌شود.',
    impactAnalysis: 'کاهش شوک‌های هیجانی ناگهانی، اما ضرورت حفظ حداقل ۳۰٪ دارایی امن طلا و درآمد ثابت به عنوان سپر دفاعی.',
    affectedMarkets: ['طلا', 'دلار آزاد', 'بورس'],
    tags: ['ژئوپلیتیک', 'دیپلماسی', 'تنش منطقه‌ای'],
  },
];

export const initialSystemicRisks: SystemicRiskItem[] = [
  {
    id: 'risk-1',
    title: 'تنش‌های سیاسی - نظامی منطقه‌ای',
    category: 'political_military',
    categoryLabel: 'سیاسی و نظامی',
    riskLevel: 'high',
    riskScore: 72,
    trend: 'stable',
    summary: 'تنش‌های ژئوپلیتیک و تحولات خاورمیانه همچنان به عنوان متغیر اثرگذار بر حباب سکه و نوسانات نرخ ارز عمل می‌کنند.',
    keyTriggers: ['رخدادهای نظامی منطقه‌ای', 'بیانیه‌های نهادهای بین‌المللی', 'نوسان نرخ بیمه کشتیرانی خلیج فارس'],
    mitigationStrategy: 'تخصیص پله‌ای پویا به صندوق‌های طلا (عیار) متناسب با شدت سیگنال جهت جذب تکانه‌های ناگهانی و پوشش تورم.',
    affectedAssets: 'صندوق طلای عیار، دلار و تتر',
    lastAssessedJalali: getLiveJalaliDateString(0, true),
  },
  {
    id: 'risk-2',
    title: 'سیاست‌های پولی انقباضی و نرخ بهره بین‌بانکی (CBI)',
    category: 'monetary_cbi',
    categoryLabel: 'پولی و نرخ بهره',
    riskLevel: 'moderate',
    riskScore: 54,
    trend: 'falling',
    summary: 'نرخ سود اسناد خزانه (اخزا) در محدوده ۲۹٪ و نرخ بین‌بانکی ۲۳.۷٪ تثبیت شده که جذابیت صندوق‌های درآمد ثابت را بالا نگه می‌دارد.',
    keyTriggers: ['حراج‌های هفتگی اوراق دولتی', 'سیاست کنترل ترازنامه بانک‌ها', 'نرخ سود سپرده‌های خاص'],
    mitigationStrategy: 'پارک ۱۰۰٪ سرمایه آزاد در صندوق درآمد ثابت افران با بازدهی روزشمار بالای ۳۰٪ مؤثر به عنوان پناهگاه امن سرمایه.',
    affectedAssets: 'صندوق افران، سهام بانکی و ریالی',
    lastAssessedJalali: getLiveJalaliDateString(0, true),
  },
  {
    id: 'risk-3',
    title: 'نوسانات نرخ ارز و شکاف نیما با بازار آزاد',
    category: 'exchange_rate',
    categoryLabel: 'ارزی و تسعیر',
    riskLevel: 'moderate',
    riskScore: 58,
    trend: 'falling',
    summary: 'با راه‌اندازی بازار توافقی، فاصله نرخ نیما و آزاد رو به کاهش است که ریسک نااطمینانی شرکت‌های صادراتی را کاهش می‌دهد.',
    keyTriggers: ['عرضه نفت و میعانات در بورس انرژی', 'تحولات بازار حواله دبی', 'مقررات بازگشت ارز صادراتی'],
    mitigationStrategy: 'تنوع‌بخشی پویا بین سپرده‌های با سود تضمینی و دارایی‌های رشدیافته متناسب با سیگنال‌های روزانه.',
    affectedAssets: 'سهام صادرات‌محور، صندوق توان، تتر',
    lastAssessedJalali: getLiveJalaliDateString(0, true),
  },
  {
    id: 'risk-4',
    title: 'نوسانات کلان اقتصاد جهانی و تصمیمات فدرال رزرو',
    category: 'global_macro',
    categoryLabel: 'کلان جهانی',
    riskLevel: 'low',
    riskScore: 35,
    trend: 'falling',
    summary: 'احتمال کاهش نرخ بهره فدرال رزرو موجب تضعیف دلار جهانی و تقویت قیمت فلزات اساسی، نفت و طلا شده است.',
    keyTriggers: ['داده‌های اشتغال غیرکشاورزی آمریکا (NFP)', 'شاخص قیمت مصرف‌کننده (CPI آمریکا)', 'رشد اقتصادی چین'],
    mitigationStrategy: 'استفاده از مومنتوم انس جهانی طلا در صندوق‌های طلای داخلی با خرید پله‌ای.',
    affectedAssets: 'انس طلا، مس و آلومینیوم، بیت‌کوین',
    lastAssessedJalali: getLiveJalaliDateString(0, true),
  },
];

export const initialAiDailySummary: AiDailySummary = {
  regime: 'bullish_expansion',
  regimePersian: 'انباشت محتاطانه بر مبنای سیگنال‌های پویا',
  overallSentimentScore: 78,
  executiveSummary: `بر اساس تجمیع داده‌های ۴۱ شاخص ورودی، مدل رژیم مارکت در وضعیت «انباشت محتاطانه (Cautious Accumulation)» قرار دارد. سیستم S1 هیچ سبد دارایی با وزن ثابت ندارد؛ بلکه اولویت نخست، حفظ ارزش اصل سرمایه و پوشش تورم است. تمام سرمایه آزاد ابتدا در صندوق درآمد ثابت افران پارک شده و در صورت تایید سیگنال قوی در بازارها (مانند نمره ۹۰ طلا)، سرمایه به صورت پله‌ای و تدریجی به دارایی پیشتاز منتقل می‌شود.`,
  macroEconomicView: `سیاست‌های ارزی اخیر بانک مرکزی در راستای توسعه بازار توافقی و کاهش رانت شکاف نیما با بازار آزاد، چشم‌انداز سودسازی شرکت‌های صادراتی بورس را به طور معناداری بهبود بخشیده است. از سوی دیگر، کنترل نسبی رشد نقدینگی مانع از جهش‌های کنترل‌نشده هیجانی گردیده، اما چسبندگی انتظارات تورمی کماکان طلا را به جذاب‌ترین پناهگاه سرمایه تبدیل کرده است.`,
  bourseAndCryptoOutlook: `در بازار بورس تهران، افزایش ارزش معاملات خرد به بالای ۸ همت و سرانه خرید مثبت حقیقی‌ها، تداوم روند مثبت کوتاه‌مدت را تأیید می‌کند. در صورت تثبیت، ورود پله‌ای مجاز خواهد بود. در بازار کریپتو، بیت‌کوین به دلیل نمره کمتر از ۶۰ فعلاً در فاز عدم اقدام قرار دارد.`,
  goldAndForexOutlook: `طلا با ثبت بالاترین امتیاز سیستمی (۹۰/۱۰۰) پیشتاز بلامنازع است. هم‌افزایی رشد انس جهانی طلا و تقاضای صندوق‌های طلا در بورس کالا، صندوق عیار را در اولویت اول ورود پله‌ای قرار داده است. با این حال، تمامی خریدها به صورت پله‌ای و با کسر از نقدینگی افران مدیریت می‌شوند.`,
  systemicRisksVerdict: `ریسک‌های سیاسی و منطقه‌ای در سطح «متوسط به بالا (۷۲٪)» ارزیابی می‌شوند اما به دلیل تسلط سازوکارهای تثبیت بازار، احتمال شوک سیستمی کنترل شده است. در پورتفوی کاغذی ۱ میلیارد تومانی، پارک کامل سرمایه در افران حداکثر نقدشوندگی و بازدهی روزشمار بدون ریسک را فراهم کرده است.`,
  tacticalPlan: [
    {
      priority: 1,
      step: 'ورود پله‌ای به صندوق طلای عیار بر مبنای سیگنال قطعی طلا (۹۰/۱۰۰)',
      targetAsset: 'صندوق عیار (Ayar)',
      rationale: 'بهره‌مندی حداکثری از روند صعودی طلا با خرید پله‌ای و اجرای سفارش بر مبنای قیمت پایانی فردا.',
      timeframe: 'کوتاه‌مدت و میان‌مدت',
    },
    {
      priority: 2,
      step: 'پارک سرمایه تخصیص‌نیافته در صندوق درآمد ثابت افران',
      targetAsset: 'صندوق افران (Afran)',
      rationale: 'کسب بازدهی روزشمار سالانه بالای ۳۰٪ موثر و حفظ آمادگی کامل برای ورودهای پله‌ای بعدی.',
      timeframe: 'مستمر و پیش‌فرض سیستم',
    },
    {
      priority: 3,
      step: 'پایش مستمر بورس تهران جهت صدور پله سهامی (صندوق خبرگان)',
      targetAsset: 'صندوق خبرگان',
      rationale: 'ورود پله‌ای در صورت تداوم ارزش معاملات خرد و تثبیت شاخص کل بالای مقاومت‌ها.',
      timeframe: 'کوتاه‌مدت',
    },
    {
      priority: 4,
      step: 'پایش کریپتو برای عبور نمره بیت‌کوین از ۶۰',
      targetAsset: 'بیت‌کوین (BTC)',
      rationale: 'عدم اقدام در شرایط فعلی؛ فعال‌سازی سفارش آنی به محض دریافت سیگنال تایید.',
      timeframe: 'مشروط به سیگنال',
    },
  ],
  keyRules: [
    'عدم استفاده از سبد دارایی با اوزان ثابت؛ تخصیص‌ها کاملاً پویا و سیگنال‌محور هستند.',
    'اولویت اول و قطعی: حفظ ارزش اصل سرمایه، سپس پوشش کامل تورم.',
    'ورود به دارایی‌ها منحصراً به صورت پله‌ای (۱۰٪، ۱۵٪، ۲۰٪، ۲۵٪ یا ۳۰٪) از محل کسر نقدینگی افران انجام می‌شود.',
    'خروج خودکار و بازگشت کامل سرمایه به افران در صورت فعال شدن حد ضرر، تریلینگ استاپ یا هشدار اضطراری SRI.',
  ],
  aiModelSignature: 'System S1 AI Synthesis Engine v2.4 (Gemini Pro Fine-tuned for Persian Financial Markets)',
  generatedTimestamp: `${getLiveJalaliDateString(0, true)} ${getTehranTimeString(true)}:00`,
};

